### ISSUE TITLE
Write a new !ask tag

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/bot#1111]
We used to have a tag called `!ask` which was designed to tell people the basics of how to ask a good question.

![image](https://user-images.githubusercontent.com/2098517/90335426-495bc300-dfd5-11ea-9de2-2d1aafb13789.png)

The problem was that we saw a lot of users abusing this tag. As soon as someone asked a less-than-perfect question in our community, other members would throw themselves at the keyboard to `!ask` that stupid user right in their stupid face.

This didn't harmonize well with the kind of culture we're trying to build, and so we decided (in https://github.com/python-discord/organisation/issues/270) to remove this tag from the bot.

## So why does this issue exist?
Well, we might be open to reintroducing the tag (or a similar tag of a different name), but we need to do something to try to prevent it from being abused. If you'd like to have a go at this, this is the issue for you.

## So what do I do?
You need to solve the puzzle of how we can create a toxicity-proof version of this tag. Here are some ideas:
- Perhaps the tag needs to be shorter, to ensure people actually read it.
- Perhaps the tag can be "de-weaponized" so that it's less applicable to situations where the user has "made a mistake". The old version had a number of bullet points which served to instruct the user on what not to do. That means, whenever a member did something that the tag said not to do, you could throw the tag in their face.
- `!ask` is a pretty common tag to have on other support servers, and some of these communities may not share our emphasis on a toxicity-free environment. This means that some of our users may unwittingly be bringing some of their bad habits from other communities into ours. Maybe this can be remedied by simply renaming the tag to something else?

**Comment by Objectivitix** [comment]
ah... this was already considered, i'm way too late xD

**Comment by Kronifer** [comment]
would you mind if I take this on? I was thinking we could have some points of what you should do rather than what you shouldn't do

**Comment by jb3** [comment]
None of the proposals put forward after the removal of the !ask tag have met the criteria specified in this issue.

We currently document good asking practices in the help channels passively through the available channel embed, which summarises good asking points and also links through to our longer form [guide](https://pythondiscord.com/pages/guides/pydis-guides/asking-good-questions/) on asking good questions.

<img width="487" alt="Screenshot 2021-05-17 at 19 48 12" src="https://user-images.githubusercontent.com/20439493/118540775-d2608000-b748-11eb-8c70-cf563bf2563f.png">

Due to the lack of proposals and our existing help channel embeds summarising the content of the !ask tag in a much more friendly way I'm going to close this issue.
