### ISSUE TITLE
Whitelist modmail threads as mod channels

### ISSUE THREAD

**Issue by mbaruh** [python-discord/bot#1125]
Currently Modmail threads aren't marked as mod channels. This means that invoking the `!user` command does now show any existing notes on a user. This means that the moderator then either has to make an explicit infraction search just to make sure, or to move to a mod channel and invoke the command there (which is less desirable as we usually keep all relevant actions inside the Modmail channel).

The suggestion is to therefore whitelist Modmail channels as mod channels. As these channels are dynamic there is no static way to do so. A solution would then be to add a functionality which allows whitelisting an entire category.
This, however, will have the adverse affect of including the incidents channels which are open to Helpers. It would then be necessary to be able to exclude specific channels in the category whitelisting.

In all the proposed solution is to allow whitelisting of entire categories with the exclusion of specific channels.

**Comment by Den4200** [comment]
I don't particularly see the need to exclude #incidents or #incidents-archive, since no one is going to invoke commands in those channels. For the `!infractions` command group, we just whitelist the entire ModMail category, along with the mod channels:
https://github.com/python-discord/bot/blob/f97a5a62ab2f8e9af8a426b1ac6d9bf4896a75da/bot/cogs/moderation/management.py#L285-L297

For the user command, we currently have this:
https://github.com/python-discord/bot/blob/f97a5a62ab2f8e9af8a426b1ac6d9bf4896a75da/bot/cogs/information.py#L281

We'd have to change it to something like this:
```python
if ctx.channel.id in constants.MODERATION_CHANNELS or ctx.channel.category_id == constants.Categories.modmail:
```

Or we could just use `in_whitelist_check`.

**Comment by lemonsaurus** [comment]
yeah, just use `in_whitelist_check`, and whitelist the whole information extension. There's no reason we shouldn't have it in modmail threads.

**Comment by MarkKoz** [comment]
Using the check is uglier IMO

```py
        show_verbose = in_whitelist_check(
            ctx, 
            channels=constants.MODERATION_CHANNELS, 
            categories=[constants.Categories.modmail],
            redirect=None,
            fail_silently=True,
        )
```

vs.

 ```py
        show_verbose = (
            ctx.channel.id in constants.MODERATION_CHANNELS
            or getattr(ctx.channel, "category_id", None) == constants.Categories.modmail
        )
```
