### ISSUE TITLE
!shh Equivalent Command for Voice Chat

### ISSUE THREAD

**Issue by janine9vn** [python-discord/bot#1160]
## Description
There is currently no way to quickly silence users in voice chat with a command. This currently makes it somewhat difficult to moderate when there are a lot of users in chat talking over each other and the mods. Users also don't always pay attention to the #voice-chat text channel if mods try to de-escalate a situation via the text channel. 

This suggestion would be to implement a !shh-equivalent command that would be run in the voice chat text channels that would apply mutes or somehow otherwise silence everyone who wasn't a moderator+ in the voice chat itself. This would help the moderator de-escalate situations and effectively moderate. 

## Considerations
The implementation of this command would have to consider how to apply the silence appropriately to users in the VC as well as how to handle users leaving/joining the VC while the !shh-equivalent command is in effect.

**Comment by bast0006** [comment]
I've needed this before. If the VC gets into a heated argument very few people are going to pay attention to #voice-chat, and I've historically had to ping several of the users and wait for them to respond to that. While I could manually go about server muting them, it would make more sense to have something to do that automatically. 

I think there should also be consideration for drawing a users attention. The !shh command immediately draws attention because all conversation stops and it's right there in front of people, but a command run from somewhere not immediately visible might not be obvious. 

The !shh command currently functions by removing send messages for the verified role. This works immediately for text, how does this work on voice? If the speaking permission is disabled, does that prevent speech immediately? Cut it off? I'm unfortunately unable to test this at the moment.

**Comment by bast0006** [comment]
After some minor testing, I have discovered that stripping the "speak", "connect", "see", etc permissions for a voice channel does not trigger them to apply until a user leaves and rejoins the voice channel. That is, if you strip someone's permission to speak via editing the channel (like we do currently for text channels) they can continue to speak until they've left the channel. New users are denied the permission on join normally. 

This means if we are going to implement this, the bot would need to manually kick users, or mute them, or whatever gets decided upon individually. This could run afoul of rate limits and other ugly corners.

**Comment by HassanAbouelela** [comment]
Instead of kicking them, the bot can move them to an inactive channel, such as the AFK (or a temp) channel, then move them back. This has the added benefit of alerting the user auditorily, and with a `Suppressed` popup that something has gone wrong. If for whatever reason that fails, the bot can fall back to muting/kicking.
