### ISSUE TITLE
Message.author may return a User, which lacks some attributes

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/bot#1178]
Sentry Issue: [BOT-85](https://sentry.io/organizations/python-discord/issues/1848136266/?referrer=github_integration)

If a user leaves the guild after sending a message, `Message.author` will return a `discord.User`. This is problematic for functions that need to get roles or some other `discord.Member`-only attributes.

Unfortunately, `has_any_role` from discord.py doesn't take this into account either. I have not tested, but I believe it may be susceptible to the same error. However, it uses `Context.author` rather than `Message.author`.

```
AttributeError: 'User' object has no attribute 'roles'
  File "discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "bot/cogs/antispam.py", line 155, in on_message
    or (any(role.id in STAFF_ROLES for role in message.author.roles) and not DEBUG_MODE)

Unhandled exception in on_message.
```

**Comment by Senjan21** [comment]
By the looks of it, it has been fixed in Discord.py 1.6: 
![image](https://user-images.githubusercontent.com/53477086/106738050-bf9dc180-6617-11eb-9a7e-f1b9a71fb232.png)
Further more, after testing it with `int eval` message was proved not to update the `.author` reference to `User` object even if the author in question has left the server.
I don't think it should be occurring anymore.
