### ISSUE TITLE
Source command bug

### ISSUE THREAD

**Issue by Anubhav1603** [python-discord/bot#1195]
source command is erroring out when i searched for `get` command and thumbnail is also not working
![b](https://user-images.githubusercontent.com/57266248/94529390-4bad7000-0257-11eb-8037-ced39cc32a48.PNG)

**Comment by Den4200** [comment]
This happens because of our configured aliases.

![image](https://user-images.githubusercontent.com/52584399/94641242-b76ef780-02ae-11eb-8c41-43a1d955b9c6.png)

`!exception` and `!get` will fail because they are not actual commands, groups, or cogs - just aliases. On the other hand, `!docs` and `!tags` are both command groups while also being aliases, so those do not have this issue.

**Comment by Anubhav1603** [comment]
Ok tnx for info :)

**Comment by Den4200** [comment]
Well, this bug still needs fixing. I was just explaining why the error occurs.

**Comment by Anubhav1603** [comment]
Ok
