### ISSUE TITLE
Adjust When the Help Cooldown Role Expires 

### ISSUE THREAD

**Issue by MrHemlock** [python-discord/bot#1223]
So the current behavior of the help channel cooldown feels a bit off.  As it's written right now, a user claims a channel and then receives the Help Cooldown role.  After 15 minutes, whether or not their channel is still open, they can claim another channel.  This means that every 15 minutes, someone can open a help channel and still keep the other ones open.  

I propose that we either link the person with their channel and only start the 15 min cooldown after the channel has been closed, or do something similar but have a second role, Help Channel Claimant (or something better).  While it's likely uncommon for this to happen, there have been instances of it popping up.  People who feel like their question isn't getting seen or that they're being ignored are more likely to do this.

**Comment by mbaruh** [comment]
I'm not sure about this. Wouldn't that create more situations where someone can't ask their question because they're on cooldown? I think I would rather someone opened a second help channel than someone not being able to ask their question.

As an alternative, if someone opens a second help channel, we could automatically close the first one.

**Comment by wookie184** [comment]
I agree with mbaruh that people may often want to follow up a question soon after closing a channel, so I don't think always having to wait 15 minutes after closing your channel is great.

I also don't really like the idea of automatically closing the first channel, I don't think people would expect this to happen and I reckon people would end up accidentally closing active channels and getting confused.

That said, I don't see a reason a user should need to have two channels open at once, so I'd say a good condition for being able to open a new channel would be if they don't currently have a channel open and it's been 15 minutes since they *opened* a channel.

**Comment by mbaruh** [comment]
This does sound like a good idea. It would only require changing the condition of when a user is able to see the available help channels and the cooldown channel, and slightly reword what's written in the cooldown channel.

**Comment by lemonsaurus** [comment]
I think this tries to solve a problem we don't have. Is anyone really abusing this to create lots of channels? Does it matter if some members occasionally have two channels open?

Imagine a member who has received an answer in his first help channel and now needs help with a second, unrelated matter. He's not aware that there's a `!close` function because he's new to the community, and has observed that his previous help channel just closed automatically after a while, so he's decided to wait until this one also closes automatically.

Now he tries to open a second help channel for help with this other matter, but oops, it's not possible! Because we don't have complete control of the Discord interface, we can't display a relevant error messages, so the member is left wondering why he can't open a new channel, or worse, under the impression that our help system is broken.

I think we should have a damned good reason if we're gonna add any complexity to our help channel system, and this isn't a damned good reason.

**Comment by wookie184** [comment]
I think having a one channel at a time system is most intuitive, and the cool down is mainly there to stop people spam opening and closing channels (maybe it could even be reduced with this proposal).

I agree that the problem it is solving is a fairly small one, but it does still happen. From what I've seen nearly all of the people who have two help channels open at once are asking the same question in both (granted that is purely anecdotal and someone asking the same question would likely be more noticeable than someone using two different channels for a valid reason).

I also think this new proposal could even be a benefit in the scenario you mention. Maybe the person's new question would benefit from the context of the previous help channel? The person that helped them in their previous channel might also know the answer to the new question. And knowing to use the `!close` command is helpful for keeping the system cleaner (less channels for people willing to help to sift through).

That said, I do see your points. I still think it would be an improvement, but I agree that it would add some complexity to the system.

**Comment by Inheritanc-e** [comment]
I quite like this idea, because there isn't really a situation where the user would need more than one help channel.
If they would have another question then they should feel free to ask them on the same channel.

**Comment by Den4200** [comment]
This has already been actioned.

**Comment by swfarnsworth** [comment]
@Inheritanc-e we had a discussion about this in a staff meeting. This is what I wrote after that meeting:

> There seems to be consensus that users receiving help in multiple channels concurrently is bad, but Ves raised the point that sometimes a channel will be inactive for a few minutes and another user will move in and receive help. We wouldn't want to shut those conversations down even if they weren't following the correct help channel flow. Unfortunately there may not be a solution to people having multiple channels that doesn't have more adverse consequences than it solves, but I suppose we can leave this issue open for a bit to see if someone has another idea.

We did end up fixing a bug where the cooldown would not be removed if a staff member closed their channel and left it at that.
