### ISSUE TITLE
!reddit subcommands are ambiguous, or not updated

### ISSUE THREAD

**Issue by adhikariprajitraj** [python-discord/bot#1236]
![image](https://user-images.githubusercontent.com/57715196/95950198-d5db0400-0e13-11eb-8441-9874f68a2964.png)
## The command here suggests that you can see the posts of the Reddit by the command `!reddit daily [subreddit=r/Python]`, but it doesn't work. It works when we input `!reddit daily subreddit_name`.
![image](https://user-images.githubusercontent.com/57715196/95950502-60bbfe80-0e14-11eb-83a4-b06fa4b63190.png)

![image](https://user-images.githubusercontent.com/57715196/95950451-46822080-0e14-11eb-8fa3-e804615a453f.png)

**Comment by spitfire-hash** [comment]
I do not think it's ambiguous. It means that if no arguments passed(only `!reddit daily`) it will send top posts from "r/Python".

**Comment by Tisawesomeness** [comment]
The syntax is ambiguous because it has a mix of syntaxes. `[...]` means the argument is optional and is used often in command help/man pages, while `subreddit=r/Python` is Python syntax for a default named argument, which could also be interpreted to mean "you have to include `subreddit=` in the command".

I think it would be clearer to have the command look like `!reddit daily [subreddit]` and add a notice that says "If no subreddit is specified, r/Python is the default" or something similar.

**Comment by MarkKoz** [comment]
I think the same people who would confuse the meaning of `subreddit=r/Python` in this context would also confuse the meaning of `[...]` for optional anyway.

**Comment by wookie184** [comment]
Closing this as I don't think there's a good alternative to the current behaviour, and the current behaviour also seems fine. This feature was also moved to sir-lancebot.
