### ISSUE TITLE
Changes to ytdl tag

### ISSUE THREAD

**Issue by AG4lyf** [python-discord/bot#1255]
As everyone knows that yt-dl github was taken down by DCMA. https://github.com/ytdl-org/youtube-dl/
It predicts more incoming projects like yt-dl.
So as discussed here https://discord.com/channels/267624335836053506/429409067623251969/769499606274015242
The tag can be more generalized.
I personally have no suggestion /s.

**Comment by jb3** [comment]
This is not yet necessary.

YTDL still exists and is available for download, even if the source is not on GitHub. I don't think we need to document that.

Right now, there is a lot of uproar against this and I would not be surprised if the YouTube-dl team submit a counter notice to the DMCA claim received from RIAA.

Let's hold off on this for a couple of months and reassess then what the situation with YouTube-dl is. The existing tag still conveys useful information.

**Comment by jb3** [comment]
Reopening since myself and AG seem torn on this issue.

YouTube DL is the biggest problem that we see in our server, if we want to generalise then I'm fine with the proposal of adding a "or any similar software" clause or something, but I think that ultimately the tag is built to target a specific problem we see within Python Discord.

**Comment by jb3** [comment]
Closing this again since as expected a sufficient counternotice was received by GitHub from the EFF on behalf of the YouTube-DL maintainers.

More information can be found in the [GitHub Blog](https://github.blog/2020-11-16-standing-up-for-developers-youtube-dl-is-back/), the couter notice can be found [here](https://github.com/github/dmca/blob/master/2020/11/2020-11-16-RIAA-reversal-effletter.pdf).
