### ISSUE TITLE
Add ability for mods to shut down a voice channel

### ISSUE THREAD

**Issue by mbaruh** [python-discord/bot#1282]
Mods should have the ability to prevent access to the channel, and boot anyone inside.
They currently have the ability to disconnect users one by one, and admins can revoke role perms, but it should be a simple command.

**Comment by Den4200** [comment]
Related to #1160

**Comment by HassanAbouelela** [comment]
I'm working on implementing this, and want thoughts on implementation. Right now the command only mutes the channel it was invoked in, but there would have to be some form of channel parsing for VC. I implemented a prototype for that ([see branch](https://github.com/HassanAbouelela/bot/tree/voicechannel-mute)), but I enabled it for text channels too. 

Should text channels fall under this modification or not? On a more specific implementation detail, I have it notifying in the invocation channel, as well as the muted/unmuted channel (VC relays to the voice channel specific text channel). Any other ideas for how to structure this? 

A possible alternative I haven't looked at would be having a separate mute command for VC that mutes the author's channel. I didn't go with this approach however because it introduces an extra command unnecessarily, and the author would have to join the channel, compared to getting trusted reports and invoking it.

Note: I have not yet implemented the actual muting of members as detailed in #1160, just role permission modifications.

**Comment by mbaruh** [comment]
@HassanAbouelela Sorry only saw your comment now. I don't think it should mute anyone, it just needs to lock the channel (which could be translated into revoking connect permissions for Voice Verified in that channel), and then disconnecting everyone in it.

I wouldn't mind it being a separate command, but I'm not sure I understood your proposed alternative.

**Comment by HassanAbouelela** [comment]
What I was getting at was that the channel would still maintain its members, but revoke all speaking permissions (and move the members to sync the new permissions). This could be useful if the silencing is for a short period, or just to get an announcement out or something.

I am not fully aware of what exactly this will be used for, so if you think just removing all members is better, I'd be happy to rewrite it to that instead.

**Comment by mbaruh** [comment]
I agree that silencing for a short duration could be useful and in that case there's no reason to disconnect anyone, and there's another issue for that (which I see you replied on).

In other instances we would just want to complete shut down the conversation for a while, in which case disconnecting and disallow people to reconnect for a bit would be preferable.

**Comment by HassanAbouelela** [comment]
I'll add an optional parameter to disconnect everyone then.
