### ISSUE TITLE
Creating a Bounty Board Leader Board

### ISSUE THREAD

**Issue by MrHemlock** [python-discord/bot#1298]
After a discussion in the Admin meeting, we've decided to expand the Bounty Board and integrating a leader board into the whole process.

My thoughts are as follows:
- The board should be linked to GitHub so that we can track the PRs (ideally completed) and code reviews.
- The board should have 4 columns: Username (GitHub and/or Discord), number of PRs, number of code reviews, some sort of scoring combining the two.

Scoring is something I want input on.  My current thinking is 2 points for PRs and 1 point for reviews.

We also need to determine how we track PR scores and code review scores.  

- Should we only accept merged PRs?  If so, should code reviews also only be tallied if they are part of a completed one?
- Do we require more than a "lgtm" review for it to count?  We've all had instances where there really wasn't anything that needed changed, so I want to hear some opinions on that.  

I'd love to hear any other ideas, input, concerns, etc.

**Comment by gustavwilliam** [comment]
I have a few questions:
- Would this be specifically for things on the bounty board or on the repos in general?
- In what channel would this leaderboard be?

The reason I bring up the second question is that the `Development` category is getting quite large. If we want to add another channel, like `#dev-leaderboard`, we may want to consider splitting the category up into multiple parts. This would probably mean a `Dev Info` and `Dev Discussion` category, but the exact name is a later question.

I also have a worry about this becoming a competitive game of sorts. I wouldn't like for us to get 2 PRs instead of 1, just because it gives more points, or that people do code reviews in more chunks in order to get to a higher position on the leaderboard. This is connected to our concerns with having a public "Hacktoberfest Reviewfest" and giving out prizes to people who are the best according to certain metrics. It may increase spam or low quality activity as well as motivating people through some rank instead of a desire to help out.

I'm not dismissing this idea entirely, but we would need to be careful with how we implement it. At the end of the day, we're looking for high quality and persistent contributors — not people who only strive to "win" and get to the top of the leaderboard in some sense. I like the general idea of an incentive like this, but I'm afraid we may not get the results we're hoping for.

**Comment by Akarys42** [comment]
I have the same concerns as Vest. 

This might just turn into a perpetual Hacktoberfest 2019, with the flood of more or less polished PRs, where contribs will just want to see their name on the leaderboard, without especially looking to contribute in a meaningful way. 
This is even scarier if we include reviews, as we would have people just looking to earn a point, but not actually review the code, or just leaving approvals without even knowing what the PR is about. 
At the end of the day, I think we would just end up with a lot more work on Core Devs who will have to manage all of this and make sure that everything wasn't done just to get a point but to actually contribute in a meaningful way. 

I think we shouldn't have such a leaderboard, or at least not in this format, for the same reason we don't want a ranking or a reputation system in the help channels, even more if we are going to have a public leaderboard. 
I'm not saying this is a bad idea per se, but with this format, I'm afraid it will do more harm than good as we had during the Hacktoberfest 2019.

**Comment by RohanJnr** [comment]
I agree with Akaryas42 and Vest here.
Instead of having a user based leaderboard, we could keep track of the number of PRs, code reviews, additions, and deletions(if possible) done per month, more like statistics keeping track of GitHub activity.
This will not highlight any user(s) and will not lead to competitiveness.
This data can be displayed every month in the #dev-announcements channel.

Note: We have already seen such a thing at the end of hacktoberfest when Joe posted October's GitHub activity.
![image](https://user-images.githubusercontent.com/37217450/99965566-0753d180-2dbb-11eb-859c-2689cb2001bd.png)

**Comment by ks129** [comment]
I think we should have leaderboard for Contributors role owners, as when they got role, this means that user have already made good contributions and (hopefully) don't start making flooding PRs and reviews.

**Comment by Akarys42** [comment]
Ks made a really good point, in my opinion, restricting it to Contributors sounds like the way to go.

**Comment by SebastiaanZ** [comment]
The current idea we discussed in the admin meeting was indeed to go for a contributors+staff board.

I trust our staff members and contributors to not act to the detriment of our projects and, frankly, if they would do that, they should not have the contributors or staff position. In any case, if we do have concerns about the conduct of contributors/staff members in regards to the board, we can discuss it with them. It's not like we're working with a group of strangers.

**Comment by janine9vn** [comment]
I think we should adjust the scoring system a bit to incentivize reviews a bit more. In the ideal world we should be doing more code reviews than actual PRs. 

So maybe flipping the weight or having it be 1.5 pts for a code review and 1 pt for a PR.

**Comment by gustavwilliam** [comment]
@janine9vn I like the idea of incentivizing the reviews. The question is how that would look in practice.

Imagine that you get 1.5 points for a review and something requires 3 rounds of reviews. That would mean 4.5 points to the reviewer and 1 to the person who wrote the code.

Maybe keeping it 1:1 would work better, but that sends a signal that we care about them equally. Do we really, or maybe it's better to test this out with an even higher score for reviews, like you proposed. Either way, we should vary it depending on the need as well.

**Comment by janine9vn** [comment]
I don't think it should necessarily be points per review. It should be a "did you review this PR (however many rounds it takes" and help it get approved? In my mind a code review is not a single round of review, but working with the PR owner to fully review the code and get it in a good place.

**Comment by gustavwilliam** [comment]
I agree about that in theory, but I'm not sure how that could be automated.

If we only count the fact that they've started a review, isn't that saying that we'd rather see you review a little bit on more things, instead of in-depth reviews on fewer things? What this boils down to is a question of quantity versus quality.

As we've talked about a lot, our contributors and staff members will probably be sound in the reviewing, but I think it's worth pointing out that there may be such drawbacks with a system like that.

**Comment by RohanJnr** [comment]
I have been messing around with the GitHub API a bit and especially this endpoint: 
https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls#reviews

In the API response, the list of users along with the state of the review is mentioned. we can use the state of the review to determine whether the reviewer gets points or not.

#### The following are my opinions:

##### Condition to get points: 
- If state = APPROVED or state = CHANGES_REQUESTED.
  - I am considering both the states because reviewers do put in the time to pull the PR to their local machine and test it.
-  If the reviewer is a contributor or above.
- The reviewer should not be the PR author.

Here is the sample JSON response I got from pulling the reviews of #1165 if anyone is interested.
https://pastebin.com/KWLjrejN

##### Answers to a few possible concerns:
- As @SebastiaanZ mentioned about the trust of the contributors, hopefully, we won't be seeing any spam reviews from the contributors.
- Does even a single comment review count? In my opinion yes, some PRs might be close to flawless but do need the approved state from a reviewer and there might be a small nifty typo or a small change required.
- Do multiple reviews on the same PR yield more points? No, 1 point for 1 PR.

**Comment by gustavwilliam** [comment]
If we are intending for this leaderboard to be a separate channel, it'll get a bit messy in the dev category. This would be the layout (the exact order of channels isn't important, but I find this one to make the most sense — alternatively moving `#dev-log`):
<img width="240" alt="Screenshot 2020-11-23 at 19 32 05" src="https://user-images.githubusercontent.com/65498475/100000909-93b5c280-2dc2-11eb-87e9-80ddd4782fe7.png">

Instead, I propose the following option, where we split it into two logical categories:
<img width="240" alt="Screenshot 2020-11-23 at 19 30 02" src="https://user-images.githubusercontent.com/65498475/100000727-49ccdc80-2dc2-11eb-9742-7d9f568f849b.png">

**Comment by RohanJnr** [comment]
I would suggest having the leaderboard at the top of  #dev-bounty-board. The channel does not get flooded with messages as solved issue messages get deleted and the bot can constantly update the leaderboard by updating the leaderboard message.

**Comment by gustavwilliam** [comment]
I'd be fine with that. The exact order doesn't matter too much to me in the info category.

**Comment by MrHemlock** [comment]
Something to keep in mind is that this leaderboard is likely to only be for staff and contribs.  It's more of an internal fun thing for us.  The Bounty Board, however, will be made public.  This has been decided outside of here after some additional discussions.

**Comment by Akarys42** [comment]
With `#dev-core`  and `#dev-ops`, the category is cluttered enough to deserve a split I think, even if most of them are hidden to normal users.

About the scoring part, I'd say that 1:1 would be a good start, and we can try more scoring methods later.

**Comment by mbaruh** [comment]
With the bounty board archived I'll close this now. Can be re-opened if becomes relevant again.
