### ISSUE TITLE
Add Bounty Leader Board Statistics to the `!user` command

### ISSUE THREAD

**Issue by MrHemlock** [python-discord/bot#1299]
Requires #1298 to be completed before this can be tackled.

Since we're going to be creating the leader board, it would be nice for users to check their own individual rank or total PRs and reviews via the `!user` command.  While they will be able to see a leaderboard, we may only have the top 10 or 20 listed, so in order for people to see where they stand, it may be good for people to see what they have.

As stated, this would require the leader board issue to be completed first.  In the meantime, some input and ideas on this would be encouraged so this can be fleshed out and ready to go when the time comes.

**Comment by gustavwilliam** [comment]
We should probably keep this quite simple, since the `!user` command isn't a fully fledged review checker command. Here's my view on this:

### User command
We could add a contributions category in the embed, where we display very basic data, like total number of contributions and contribution rank in the leaderboard — or we could make individual fields for it.

However, we must remember that most users checking the user command aren't looking for their full contributions history. Most people haven't even contributed. Adding *some* field about this could make them slightly interested in what contributing is really about, but we should not spam them with info. One or a maximum of two fields would probably be optimal.

### Contributions stats command
This one is an idea that would be a great complement to the basic data in the user command — especially for people who are contributing regularly and would like to check their progress.

The idea is that we'd add a command for checking slightly more info about your contributions to the PyDis repos. We could send data like issues opened, PRs opened, leaderboard position, total PR reviews and whatever else we might find interesting. This includes time dependent data like "PRs in the last month" and maybe even a simple contributions graph. Whatever we might find interesting.

I quite like the idea of this command. We could possibly mention the command as a way to get more stars in the `!user` embed, straight under the basic contributions stats. That would give contributing a more prominent place in our community, but might clutter things up slightly. It's an idea worth considering.

### Final remarks
Depending on the implementation of the added field(s)/category in the `!user` embed, we may actually be able to complete this before a potential leaderboard. That simply depends on what we decide to create.

**Comment by mbaruh** [comment]
With the bounty board archived I'll close this now. Can be re-opened if becomes relevant again.
