### ISSUE TITLE
Command to let mods add video role for a user to share their screen for voice chat help

### ISSUE THREAD

**Issue by MrHemlock** [python-discord/bot#1343]
Streaming and video permissions are currently disabled for non-staff or contributors.  However, at times it's beneficial for users to share their screen to show the errors that they're getting.  This currently requires an admin to apply the Video role to the person.  Admins aren't always around, so this makes things difficult.  

My proposal is that we should have a command to let mods+ be able to give the video role.  This has a potential pitfall in that people may forget to remove it.  My solution to that is that the role should be revoked as soon as the screen share starts.  The user's stream will not be closed even if their permissions are revoked.  Additionally, we can set a timeout that removes the role if they don't start a stream in say... 5 to 10 minutes (the amount of time is just off the cuff.)

Command details summary:

- Grants the Video role to the user (would be the User ID, mention, etc)
~~- Waits to see when the user starts a stream and removes the role~~
~~- If the user does not start the stream after x minutes, remove the role~~
- Removes the role after a set amount of time
- Also has a command for revoking the role immediately

Should be relatively simple.

**Comment by MarkKoz** [comment]
See #1303

**Comment by swfarnsworth** [comment]
When you were helping a user this morning, and they had screenshare on, I completely forgot that you had to have been the one to grant that permission. I'm not completely sure what that says about how obviously (or not obviously) ripe for abuse letting users screenshare is.

That being said, I think we would need to agree on what the moderation policy should be for different types of potential abuse. I think it's obvious that streaming porn would result in a permanent ban if we were able to verify as much. There are probably some less obvious cases. And verifying that abuse is taking place at all would also be difficult given the limitations of the client.

How would users signal to moderators that they want to get temporary screenshare permission? I don't want it to be via an at-Moderators ping because we typically see those as urgent requests for intervention, and I don't want to lose that association. A command that triggers an at-here ping in some existing or new channel might be better, but could result in user dissatisfaction if no one is there to immediately service that request. Knowledge that they can obtain screenshare permission might also spark at-Moderators pings if they don't know or don't care that another system exists, or if they don't get an immediate response.

For the average good-faith user, I do want them to have screenshare permission when it would be helpful for them, so this comment is not intended to cast negative light on the entire concept.

**Comment by MrHemlock** [comment]
I think we can still enforce the "there needs to be an adult in the room" theory we currently have in that we won't be giving the permissions unless we're there.  Strangely enough people haven't done pinging me for the rights to stream.  But I know that's anecdotal.  I do see it as a valid concern. 

The main thing is that I can't think of a better way to handle this.  I'm typically the only admin who hangs out in there (not a rip on the others, just what I do), so I'm really the only one that can grant the role.  However we do often have a few mods that come in from time to time, and I feel like it'd be wise to give them a tool that lets them grant it when the need arises.  I feel bad for the users that it really only seems to be when I'm around is when they can use it for help.

**Comment by swfarnsworth** [comment]
@MrHemlock does that mean that we'd roll out this feature "silently"? That is, no announcement and with no system for requesting  these temporary permissions? I suppose I'd be fine to trial that and see if we ever get an influx of users pinging the mods asking for permissions, and re-evaluate from there.

**Comment by MrHemlock** [comment]
@swfarnsworth I think that'd be my preference for now.  There are some features we really don't want to or need to blatantly advertise.

**Comment by MrHemlock** [comment]
The PR has been tweaked to fit both the work that has been done on the linked PR and after discussion of the needs and wants of the mods who will be using it.
