### ISSUE TITLE
Implement a better system for keeping track of alternate accounts

### ISSUE THREAD

**Issue by swfarnsworth** [python-discord/bot#1353]
Currently, if we believe that two or more accounts belong to the same person, we issue a note infraction for each account stating which other account IDs we believe to belong to that person, which requires a series of relatively similar commands that are ripe for error. It also makes it more difficult to respond to incidents pertaining to such user.

I think we need some way of documenting which accounts we believe belong to the same person and why we believe this, as well as the option of viewing a joined infraction table when querying a given user's infraction history across all their alternate accounts.

I make this suggestion with the awareness that suspected alts are not the same as confirmed alts (and it's not necessarily possible to confirm an alt), so any functionality that we design as a result of this issue should not change the way we currently approach infracting people based on infractions from suspected alts.

This issue should also await changes described in #1189.

**Comment by Akarys42** [comment]
We had a small discussion in #mods-tools a couple of days ago, and our general consensus was that we don't need something as complicated as creating a brand new infraction type, we could simply have an `!alts [greedy user...] [reason]` command that will run an `!note user1 Alt of user2, user3,.... Reason` for each user to avoid having to type that our manually.

That said, maybe we do want something more complicated? What does others think about that?

**Comment by Xithrius** [comment]
In my opinion, we don't need something more complex. *Maybe* some would want at the top of an infraction listing something like `Alts: user1, user2,...`, but at this time I don't think it's necessary. Most users who have alt accounts don't have many infractions, as far as I can remember.

> we could simply have an `!alts [greedy user...] [reason]` command that will run an `!note user1 Alt of user2, user3,.... Reason`
Having the alt command kind of act like an alias would work great in my opinion, I'd like it.

**Comment by minalike** [comment]
I am in favor of making a new record type or infraction type for storing alt accounts, and not piggybacking off the note infraction as we have been doing.

I'm envisioning this scenario: 
User A and User B are the same person, we link them in the database as relationship 1. A week later a new User C comes along and we determine that they are the same person, so we add them to that same relationship so that now all 3 users are tied to the same relationship. 

Now whenever we run the user command for any of the 3 users, there is a section on the profile (or a button leading to a new section) that there are 2 other users associated with this one.

I'd also be in favor of storing and being able to edit the reason and justification that we've determined the relationship to exist.

**Comment by janine9vn** [comment]
I'm going to pick this up as a winter holidays project I think.

The approach I'm thinking of:
- New infraction type "association" that operates kind of like a note.
    - I'll probably ask some folks for help in trying to determine how to structure this infraction type. It has some unique meta-information I'm a bit unsure how to handle wrt our current models setup.
- New moderation bot command `!association` (with aliases: `!alt`, `!alts`, `!assoc`) that will look like the following:
    - `!alt id1 id2 "these two accounts are connected for this reason"`
    - This will apply the association infraction on both accounts, with the same reason.
- When a moderator does `!infraction search`, it will **not** show all the associations alongside the infractions. Instead, I'm going to have it show on the first page "X associated accounts, Y secondarily associated connections" and that's it
- A new `!alt-info` command that will show all the account associations and their reasons. This will also show how many associates the *other* account has. For example: `!alt-info id1` will return something a listing for each associated account and the reasoning. Each associated accounts will list how many associations (minus 1 because of the current association) it also has.
- `!user` run in mod channels will show the # of associations as a typical infraction count. As a potential extra, I can add the number of additional associations those accounts have (`Associations: X (Y total secondary)`).

#### More reasoning on the alt-info command...
If we have the example of 3 accounts: id1, id2, and id3. id1 and id2 have already been marked as alts. If we mark id1 and id3 as associated, I'm specifically **not** going to apply an association between accounts id2 and id3 for a few reasons. I think avoiding doing that will make the overall implementation simpler especially for users with a large number of associated accounts and not all associations are guaranteed alts, so I'd rather not automatically run those associations.

To cover the situation of a main account having 12 associated accounts and us looking at one of those alts in isolation (we would only see 1 associated account, not showing the true nature of how many total connected accounts there are), that's where the `!alt-info` command would show many how additional connections the association-infracted accounts have.

The output would look something like...
```
**Associated accounts for id1**
<@id1> - id1

**Association ## - id2**
By: <Actor>
Issued: <Date>
<@id2> - id2
Context: "reasoning goes here"
Additional associations: ##
```
