### ISSUE TITLE
Pinned message command

### ISSUE THREAD

**Issue by anand2312** [python-discord/bot#1357]
### Invocation
`!pin <n> [channel]`
Fetches the n'th pinned message from `channel`, in an embed.
Optional argument channel defaults to the channel in which the command was invoked.

### Rationale
As tags are generally not library specific, this command could be used as an alternative to get common issues/popular guides that are kept as pinned messages in topical channels. This would let us make tags more general, while also getting the ease of access of a tag-like command. 
Moreover, regular helpers in topical channels mostly remember the order of pinned messages, so using the command wouldn't need _too_ much extra effort.
\
The main issue that I can see with this is formatting; but a good portion of messages that get pinned are well formatted, so directly dropping them into an embed wouldn't look that bad.

**Comment by HassanAbouelela** [comment]
When this was originally discussed, I raised some concerns about the numbering system not actually being functional. Tags move around, and I'd think you'd end up linking to incorrect pins a lot. There was discussion about it [here](https://discord.com/channels/267624335836053506/635950537262759947/816607665609900032).

In terms of the rationale of this issue, I don't remember if library-specific tags were a thing back then or not, but they 100% are now. We have a ton of discord.py tags (which seemed to be the main reason people wanted this pin system in the first place).

For the reasons outlined here, and because this hasn't been brought up since the issue was originally opened, I'll be closing it. If someone still thinks this system is preferable to tags and has a good implementation, it can be reopened.
