### ISSUE TITLE
Create a delete and reroll command for OT names

### ISSUE THREAD

**Issue by swfarnsworth** [python-discord/bot#1559]
We decided in a staff meeting today that there will be a new command that, for a given off-topic channel, picks a different name from the available pool and deletes the current name from the pool (rather than marking it used) and (updated 20 August) marks the removed name as "inactive" in the database. When attempting to add a name to the pool that exists in the pool as inactive, the command should fail with the bot explaining as much. One should be able to circumvent this with `forceadd`. This would be a moderator+ command that lives in the off-topic cog. 

Other details of the spec have not been decided on, including:
- The name of the command. `reroll` is a contender, though one might not infer that the command both rerolls and deletes.
- The argument that is passed to it. Should it be an integer in `{0, 1, 2}`, or should it be a channel ID? Should it be optional and in that case act upon the channel in which it in invoked?

I may be able to implement this myself, as I'm pretty much done with school.

**Comment by ChrisLovering** [comment]
cc @RohanJnr

**Comment by swfarnsworth** [comment]
@RohanJnr would like to implement this. I chatted with him earlier, and for now the specification is that `!otn reroll n` for `n in {0, 1, 2}`, though keep in mind that it will both reroll the name for that channel *and* delete the then-current name. The `n` argument will be optional when evoked in an off-topic channel.

Whoever is knowledgeable about rate limits as they apply to channel renames, I'd be interested to know if this command needs a cooldown.

**Comment by RohanJnr** [comment]
We will need a cool down, we can edit the channel 2 times before we hit a 10min rate limit cooldown.
The command can have a cooldown of 5min to avoid the rate limit.

**Comment by RohanJnr** [comment]
Do we want the cooldown for the entire command or do we want the cooldown per channel?

**Comment by swfarnsworth** [comment]
@RohanJnr whichever count cooldown pertains to.

**Comment by RohanJnr** [comment]
## Plan 1  to handle rate limits.

Store the number of times an `off-topic channel` has been edited as `times_edited` and also the `datetime` instance for the `last edit`

data structure:
```python
{
 channel_id: {
    "times_edited": int,
    "last_edit": datetime
 }
}
```
or the above can be done using a `Class` ( I have not decided which one I want to use yet).

### Conditions before editing a channel via the `reroll` command or the `daily channel name updater task`,

- if `times_edited` is `2` and 10minutes have `not` passed since the `last_edit`, then:
  - Reschedule the channel edit if it's the `daily channel name updater task`.
  - Tell the user to try the command later if it's the `reroll` command or schedule the reroll command.

- if `times_edited` is `2` and 10minutes have passed since the `last_edit`, then:
  - Go ahead and edit the channel.
  - Reset `times_edited` to 1 and store `last_edit`.

- if `times_edited` is 1, then we just edit the channel, update `times_edited` to 2, and `last_edit` to the current time.


## Plan 2
Just to set a 10minute cooldown on the reroll command.


The former allows you to edit multiple channels 2 times within 10min(mostly) and then not allowing you to edit the channels for the next 10min (to reset the rate limit cooldown) whereas the latter allows you to edit only 1 channel every 10min though easier to implement.

**Comment by swfarnsworth** [comment]
If you go with plan one, can you store that information in an async redis cache? How will you handle the daily non-deleting rerolls (since those also count towards the rate limit)?

If you're worried that plan one would slow down development too much, you can go with plan 2 for now and we can plan to migrate to plan 1 later. The underlying logic for the actual deletion-reroll should be unaffected.

**Comment by RohanJnr** [comment]
> How will you handle the daily non-deleting rerolls

I did mention it as `daily channel name updater task`.

**Comment by RohanJnr** [comment]
> If you go with plan one, can you store that information in an async redis cache? How will you handle the daily non-deleting rerolls (since those also count towards the rate limit)?
> 
> If you're worried that plan one would slow down development too much, you can go with plan 2 for now and we can plan to migrate to plan 1 later. The underlying logic for the actual deletion-reroll should be unaffected.

We can use async redis cache. I believe async redis cache does not accept dicts as a value, so maybe stringifying it and storing could work. Unless we want 2 keys for the same channel, to store `times_edited-{channel-id}` and `last_edit-{channel-id}`

**Comment by RohanJnr** [comment]
hello @swfarnsworth , can you update the issue description to match the updated implementation?

### Updated implementation
Instead of deleting the `off topic name` after re-rolling, we are gonna mark that `name` as `inactive` in the backend (database).
These inactive names will not be considered for future channel names. We are storing these to avoid similar names to be added via the `add` command as the command checks existence of similar names.

**Comment by RohanJnr** [comment]
If we reroll a channel's name, do we want to reschedule the daily OT update tasks to update the channel name 24h from the reroll, or does the channel name update at the standard time 00:00 UTC?

**Comment by swfarnsworth** [comment]
@RohanJnr I've added this to the specification:

> ...and (updated 20 August) marks the removed name as "inactive" in the database. When attempting to add a name to the pool that exists in the pool as inactive, the command should fail with the bot explaining as much. One should be able to circumvent this with `forceadd`.

**Comment by swfarnsworth** [comment]
@RohanJnr what's the status on this?

**Comment by RohanJnr** [comment]
The site pr is almost ready, current being reviewed
