### ISSUE TITLE
Wrong tooltip .mosaic

### ISSUE THREAD

**Issue by ShadowRStar** [python-discord/bot#1580]
When .mosaicing ur avatar with some wrong input u get an example with .avatar_modify Mosaic and not .mosaic

**Comment by ToxicKidz** [comment]
Hey, this is because the command itself is `.avatar_modify mosaic`, because it's in the `.avatar_modify` group. The reason you're ale to invoke like `.mosaic` is because it uses [`root_aliases`](https://github.com/python-discord/sir-lancebot/blob/main/bot/command.py#L8-L10). The qualified name for the command is `.avatar_modify mosaic`, so the tooltip isn't wrong.
