### ISSUE TITLE
Add typing feedback to !user command

### ISSUE THREAD

**Issue by JacobMonck** [python-discord/bot#1635]
# Issue
When using the `!user` command I have found that if the user isn't cached the command can sometimes take upwards of 10 seconds to give a response. So for a fix I was thinking we can add `async with ctx.typing` just so it gives the user some sort of feedback so they know the command is in fact working.

**Comment by Kronifer** [comment]
I'm not sure this is necessary, if we are going to implement this, maybe we should add it, or if not we should remove it from bot and lancebot.

**Comment by JakeM0001** [comment]
Well usually we only have it on commands that might take awhile i.e. our profile picture commands, and I think that's necessary for this command since as I said before it can take upwards of 10 to give a response.

**Comment by ChrisLovering** [comment]
I'm not against adding it, as it can sometimes take a while, especially when the user has a lot of message that need enumerating.

However, this command taking >2s usually means there's something wrong with our postgres instance (too many connections for example) which we quickly resolve, since we get notified in a devops channel.

**Comment by Xithrius** [comment]
I don't see any problem with adding this feature.

**Comment by wookie184** [comment]
I recall somebody mentioning that the main reason it takes a while is because it fetches message count from metricity. It only needs to do this in mod channels as this is the only place the counts are displayed, but it seems to make the api call anyway: https://github.com/python-discord/bot/blob/f2ef6c12b0a872413bad33186bc60bbbdd17f304/bot/exts/info/information.py#L244

Moving this to only happen after the mod channel check should speed it up in most cases, and I don't really think the typing would be needed for mods running it in mod channels.

**Comment by JakeM0001** [comment]
Yeah, that's the problem, I think we should send the embed that the user sees then we do the API call and send the embed that staff see.

**Comment by JakeM0001** [comment]
Yeah I agree.
