### ISSUE TITLE
apply_infraction assumes the user will have a mention attribute

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/bot#1681]
According to the type annotation, the `user` argument may be a `discord.Object`. This does not have a `mention` attribute. This will lead to an exception when trying to send the confirmation message or log message. I don't remember why `user` can be `discord.Object` but I think it's related to users that aren't in the guild. I haven't tested to see if it's a bug in practice, but this should be looked into.

**Comment by TizzySaurus** [comment]
I believe `discord.Object` was how you infracted users who weren't in a guild before discord.py V1.6, however 1.6 introduced lazy-fetching which will get the `discord.User` object even when the user isn't in the server.

If I'm wrong and it is still possible for `user` to be a `discord.Object` we should change `user.mention` to `<@user.id>`, since `discord.Object` does have an id attribute, and this is what `user.mention` would return.

On the other hand, if I'm correct and the user will never be `discord.Object`, then the typehint should be updated to reflect that it'll not be `UserSnowflake`, but `UserObject` (since `discord.User` won't fail). In fact, this arguably extends to the fact that `bot.converters.FetchedUser` is pointless now (again, since `discord.User` won't fail).

**Comment by TizzySaurus** [comment]
@Akarys42 has okayed-this on discord, so I'll start removing the now redundant methods.
