### ISSUE TITLE
File inside new help channel

### ISSUE THREAD

**Issue by Pandabweer** [python-discord/bot#1735]
If a user attaches a file to the message he wants to send the message will be deleted and there will never be a pinned issue.

**Comment by NIRDERIi** [comment]
![image](https://user-images.githubusercontent.com/78727420/128984723-cd217ea5-6656-4079-94d5-c7d7f45d9b68.png)

**Comment by wookie184** [comment]
Do you have a proposed fix/improvement to this? afaik it's not possible for bots to delete only attachments from user messages. I guess we could try and detect if the pinned message was deleted and try and pin the next message from the author if it was, not sure how easy that would be to implement, or if it would be worth the effort.

**Comment by Pandabweer** [comment]
I will look into it if it would be quick solution otherwise I'd agree that it will not be worth the effort.

**Comment by MarkKoz** [comment]
> I guess we could try and detect if the pinned message was deleted and try and pin the next message from the author if it was

It'd be fairly simple to make it pin the next message it receives. However, this doesn't necessarily mean the first extant message will be pinned, since a message can be deleted after more are sent. A compromise could be reached where it only pins the next message if it's going to be the first extant message for that help session. However, that would require looking up message history (requires an API call) once per pair of message deletion and message sent events unless the bot starts caching message counts for each session, but that's another can of worms.

To support the case of a message being deleted after more are sent, it would have to do an arbitrary number of searches until it reaches the start of the help session, and that sounds like a bad idea.

**Comment by wookie184** [comment]
I don't think this is worth the added complexity. When going into a new post it seems you start scrolled at the top, so it's easier to see the context of the post even without a pinned message.
