### ISSUE TITLE
Removing the dormant category.

### ISSUE THREAD

**Issue by MorgVerd** [python-discord/bot#1799]
I do not personally see any reason behind the dormant phase of a help channel. Once a question is answered, or the channel is closed, why should that help channel not then return to being available? Currently as of writing this there are only three available help channels with twenty-seven channels waiting an arbitrary amount of time to be re-opened.

Maybe I am missing the purpose behind the phase, but to me it just limits the available channels, requires more help channels as most are sitting in the dormant phase and unusable.

**Comment by Numerlor** [comment]
Moving all of the channels into the available category would push the channel list down for a lot of users

**Comment by MorgVerd** [comment]
> Moving all of the channels into the available category would push the channel list down for a lot of users

So, have less help channels. Currently there are only so many to account for the large amount in the dormant category. Without the dormant category significantly less channels would actually be needed.

**Comment by jb3** [comment]
> Currently there are only so many to account for the large amount in the dormant category. 

We don't want to delete help channels because of the archival benefits, so at peak we have seen every channel you see today in use at once.

> Without the dormant category significantly less channels would actually be needed.

This isn't so, no matter where the channels are at peak times all will be in use or all will be in available.

> it just limits the available channels

This isn't how the system works, once an available channel is claimied one of the dormant channels is revived from the dormant category and moved to the available category, ready to be entered into circulation.
