### ISSUE TITLE
Too strict markdown escape in PythonNews

### ISSUE THREAD

**Issue by Bluenix2** [python-discord/bot#1821]
The bot can be seen escaping underscores in code [in this message](https://discord.com/channels/267624335836053506/704372456592506880/885531093158215791).

The regex (if possible) should be updated to not insert `\` inside codelines or codeblocks such as (in this case) `__eq__`.

On the bright side, it did work for one ocasion I've screenshoted below!
![image](https://user-images.githubusercontent.com/38372706/132735432-6ebb1382-98b0-451c-b081-fcc60ad74970.png)

**Comment by TizzySaurus** [comment]
> The regex (if possible) should be updated not to insert `\` inside codelines or codeblocks

It should just be a matter of update the regex [here](https://github.com/python-discord/bot/blob/main/bot/exts/info/python_news.py#L79).
```py
>>> string = "Hello world `__repr__` how are _you_? I'm good _today_, but __tomorrow__ may be different, `_User`."
>>> reg = r'(?:`[^`\\]*(?:\\.[^`\\]*)*`)|([_|])'  # will get underscores and pipes that aren't in backquotes
>>> to_escape = [m.span()[0] for m in re.finditer(reg, string) if m.group(1)]  # indexes of chars we need to escape
>>> to_escape
[31, 35, 47, 53, 60, 61, 70, 71]
>>> new_str = ""
>>> for index, char in enumerate(string):
	if index in to_escape:
		new_str += "\\" + char
	else:
		new_str += char

		
>>> print(new_str)
Hello world `__repr__` how are \_you\_? I'm good \_today\_, but \_\_tomorrow\_\_ may be different, `_User`.
```
I believe this is the rough behaviour wanted, and from quick testing it does seem to also work with multi-line codeblocks.

Issues with this regex:
  - If an underscore / pipe is already escaped then it'll be escaped again (same behaviour as currently, but may want to change)
```py
>>> print(new_str)
Hello world `__repr__` how are \\_you\\_?
```
This issue could probably be fixed by changing the final if statement to something along the lines of `if index in to_escape and string[index-1] != "\\":` but don't have time to test this.

**Comment by TizzySaurus** [comment]
I've managed to confirm that the proposed change to the final if statement works, and @Bluenix2 has confirmed this is the wanted behaviour on [discord](https://discord.com/channels/267624335836053506/635950537262759947/885651332739006494) so will work on the PR.
