### ISSUE TITLE
Duckifying doesn't work for messages inside threads.

### ISSUE THREAD

**Issue by TizzySaurus** [python-discord/bot#1930]
As the title says.

An example can be found on an internal staff thread [here](https://discord.com/channels/267624335836053506/902258820561137754/902259286527311913). For those that can't view the message, it has the required amount of duck reactions but the bot didn't "duckify" it.

The issue *may* be these lines ([L168-L170](https://github.com/python-discord/bot/blob/main/bot/exts/fun/duck_pond.py#L168-L170)) but can't be sure without further investigation:
```py
        channel = discord.utils.get(self.bot.get_all_channels(), id=payload.channel_id)
        if channel is None:
            return
```

**Comment by TizzySaurus** [comment]
From #1968 (a duplicate of this issue).

![Akarys](https://user-images.githubusercontent.com/47674925/142833322-6b69356a-f2a0-4014-82d4-90e89f42c63c.png)
CC @Akarys42 @lemonsaurus

**Comment by lemonsaurus** [comment]
It was done because we wanted to be able to duck messages even if they aren't in the cache. 

With Continuous Deployments, the bot is quite frequently clearing the cache, and it would be poor user experience if it wasn't possible to duck a message just because there happened to be a redeploy right after the message.

If this isn't a problem, or if we can solve this problem without raw reactions, I'm sure that would be fine.

**Comment by ChrisLovering** [comment]
we could easily solve this by adding the guild.channels and guild.threads lists together and then using get on the channel_id.

**Comment by Akarys42** [comment]
I forgot reaction_add doesn't fire on messages outside of the cache, that's stupid. Yeah, I think searching both the channel and thread list is a good solution.

**Comment by TizzySaurus** [comment]
> we could easily solve this by adding the guild.channels and guild.threads lists together and then using get on the channel_id.

This sounds good. I'll PR this by (hopefully) the end of the week :+1:
