### ISSUE TITLE
Send a helpful message to help sessions that go unanswered

### ISSUE THREAD

**Issue by ChrisLovering** [python-discord/bot#2067]
Around 23% of help channel sessions go completely unanswered.

We have a theory that a large proportion of this stat are from people who don't ask their question well, or don't provide enough information for helpers to help them.

To try and reduce that, this issue proposes that we send a message in help channels after 15 minutes if no one other than the claimant has sent a message.

I believe this message should include:

1. An explanation that everyone here is a volunteer, and we don't have 24/7 cover, so asking your question at another time may get better results
2. Reiterate the more important points from the available help channel embed.

We should also make sure that the same person doesn't get this message multiple times, since it could become infuriating if you receive this embed every time you ask a question through no fault of your own.
To aid this, we should store claimants who receive this embed in redis, for ease of implementation.

**Comment by quintindunn** [comment]
An addition to this I thought of is when someone claims a how-to-get-help channel it could check if their initial message is in a list of common first messages like `hello`, `hi`, `help me` etc. and if it does have the bot wait say 10 seconds and if the user that claimed the channel is not typing (I believe you can check that, if you can't then have this happen after say 60 seconds of no messages) have the bot reply to the message restating:

Remember to:
• Ask your Python question, not if you can ask or if there's an expert who can help.
• Show a code sample as text (rather than a screenshot) and the error message, if you got one.
• Explain what you expect to happen and what actually happens.

**Comment by quintindunn** [comment]
Another thing I also think it should say is something a long the lines of:
"Try to write your sentences with grammar heavily in mind as it will help readability for people trying to answer your question"

**Comment by onerandomusername** [comment]
>  To aid this, we should store claimants who receive this embed in redis, for ease of implementation.

Instead of using redis, this should be stored in the database as redis is no longer being used for anything persistent.

**Comment by wookie184** [comment]
This was implemented in https://github.com/python-discord/bot/pull/2504
