### ISSUE TITLE
Command request: Add topic parameter to `!resources`

### ISSUE THREAD

**Issue by swfarnsworth** [python-discord/bot#2079]
I'd like for the resources command to have a single, optional parameter for specifying the topic. For example, `!resources data science` should return the URL for the resources page, pre-filtered to show all data science resources. This only requires appending the URL to include `?topic=data-science`.

I think trying to support more filtering options than this (like support for more than one option or settings for the other filters) would be too complicated for the command, but I can see this minimal augmentation to the existing command being used in topical channels.

If there's a consensus that we don't want this, we can close this issue without implementing it.

**Comment by swfarnsworth** [comment]
If you go into the server and run `!source resources`, it will tell you. At least I think it will.

If it's a "tag" (a command that fetches a static markdown file and displays the content), an actual function for the command will need to be defined somewhere. Try asking in #dev-contrib, in that case.

**Comment by Numerlor** [comment]
The feature could simply be implemented as tags under a new resources group, though depending on what exactly is in those tags, it could lead to some content duplication between them.

**Comment by zeph-yrus9** [comment]
Looks challenging for me, but surely i will try.

**Comment by lemonsaurus** [comment]
It is a tag, yes @swfarnsworth.

Which means, we either need to do what @Numerlor suggested and making one tag for each type in the same group, or we need to get rid of the tag and just make a regular command for this to replace it.

The latter seems simpler to me. It could simply take any input you give it and append it to the URL as `?topic=<input>`. The Resources page is made so that if you request a topic that doesn't exist, that's okay, it'll just dump the parameter and show you all the resources instead.

Additionally, there are some easter egg types... 🍋 

So I think that would be my preference.

**Comment by lemonsaurus** [comment]
Hmm, on second thought, this may have an unintended side-effect of getting in the way of how people like to use this tag today. A lot of people love throwing extra text after the invocation:
![image](https://user-images.githubusercontent.com/2098517/153630454-47394e75-8086-427a-895f-a908c5d69b0a.png)

which may cause it to break or perform strangely in interesting ways.

**Comment by Numerlor** [comment]
With the different tags I also though of changing the accompanying text of them, but looking at the resources page and how many potential filtering options there are (without combinations) it doesn't seem fitting for plain tags

**Comment by minalike** [comment]
Writing a message alongside the invocation of `!resources` is indeed very very common, as lemon pointed out.

Would it be possible to make it such that some logic is only triggered if the user says `!resources for _` ?

**Comment by swfarnsworth** [comment]
I see the problem, but I think it solves itself.

[See what happens if you click https://www.pythondiscord.com/resources/?topics=foo-bar-lol?](https://www.pythondiscord.com/resources/?topics=foo-bar-lol?)

[As opposed to https://www.pythondiscord.com/resources/?topics=data-science](https://www.pythondiscord.com/resources/?topics=data-science)

It looks like clicking a link with an invalid `?topics=` argument takes you to the resources page without any filters applied.

**Comment by zeph-yrus9** [comment]
Should we add the new !resource command to [help cog](https://github.com/python-discord/bot/blob/main/bot/exts/info/help.py#L467)?

**Comment by zeph-yrus9** [comment]
> Should we add the new !resource command to [help cog](https://github.com/python-discord/bot/blob/main/bot/exts/info/help.py#L467) at `bot/exts/info`?
@swfarnsworth ?

**Comment by iamericfletcher** [comment]
This is interesting and would like to be assigned this issue if possible? It would be my first contribution and seems to be within my skillset. Thanks!

**Comment by zeph-yrus9** [comment]
Yes, please consider @iamericfletcher 's request as I might not be able to give my attention to issue due to having session ending examinations.

**Comment by iamericfletcher** [comment]
Given the nature of the information sought by the user, I agree with @zeph-yrus9 that this command should reside in `bot/exts/info`. I've created a new file for this command on my local machine instead of adding the `!resource` command to [help cog](https://github.com/python-discord/bot/blob/main/bot/exts/info/help.py#L467).

Also, I added a method to scrape the `Topics` from [https://www.pythondiscord.com/resources/](https://www.pythondiscord.com/resources/). I plan to use this information for validation and or allow the user to query the current topics on the site by entering something like `!resources topics` or if the user enters just `!resources` include in the embed the topics available.... just spit balling at this point.

**Comment by iamericfletcher** [comment]
Hi, everyone.

Provided below is a `gif` of the progress thus far.

Note that I thought it may be helpful to write a simple method to scrape the `Topics` from https://www.pythondiscord.com/resources/ to make the `!resources` command a little more informative for the user. What do you think about this?

https://user-images.githubusercontent.com/64165327/158497321-d2329d73-06f0-43d8-8253-ed4420045168.mp4

Also, what are your thoughts on building out the command in such a way that accommodates multiple filters? 

For example: 

`!resources data science & discord bots`

would yield a hyperlink to:

https://www.pythondiscord.com/resources/?topics=data-science%2Cdiscord-bots

**Comment by Shivansh-007** [comment]
Why not just have a resource API on the site which powers this command?

**Comment by D0rs4n** [comment]
Closed by  #2117
