### ISSUE TITLE
Add dehoist command.

### ISSUE THREAD

**Issue by JacobMonck** [python-discord/bot#2091]
Originally got the idea from the Vortex bot and thought why not implement this in the pydis bot. 

Basically, Vortex's way of doing it makes you provide the character in the command then everyone who is hoisted with that character and above will be dehoisted. I don't know if that's how python discord would want to do it. I was thinking of having more of an automated command that doesn't have any character input and dehoists people with characters from a set list. Here is an example of how vortex has implemented it. ![image](https://user-images.githubusercontent.com/77035482/154340695-3c613809-da57-4124-962d-93e2048d15ea.jpeg)

**Comment by ChrisLovering** [comment]
I'm not sure how much we really care about members hoisting themselves up the member list, since you already need to scroll, ~6 pages just to get to normal members.

I don't think a command that will make that many api requests would be worth it for us, since I imagine there are easily >1k users with a symbol in their name.

**Comment by JacobMonck** [comment]
It would only initially be a problem for the first time the command is run other than that it should be fine. But I understand where you are coming from.

**Comment by wookie184** [comment]
I'll close this issue as I agree with Chris that members hoisting themselves isn't something we're worried about. There will always be people at the top of the online members list, who they are doesn't really matter.
