### ISSUE TITLE
The bot should automatically detect topics and react accordingly

### ISSUE THREAD

**Issue by amogorkon** [python-discord/bot#2127]
Using nltk the bot could automatically detect topics ( https://towardsdatascience.com/topic-modelling-in-python-with-nltk-and-gensim-4ef03213cd21 for a comprehensive intro) and either automatically suggest to move to a topical/ot channel or it could suggest to check a specific resource that might relate to the topic at hand. Of course there should be a timer (maybe 2 minutes) to avoid spamming.

**Comment by wookie184** [comment]
I'm not *completely* against this, but I think there are a few fairly major issues, such as:
- I'm not sure how accurate this could be. False positives would be pretty annoying and could just end up making the channel even more cluttered.
- Sometimes pygen is a fine place to ask a question. It's not really clear what it's purpose would be otherwise (although yes, a topical channel would usually be preferred).
- People will likely ignore it anyway - it's hard enough for a human to redirect someone, people to tend to ignore bots.

**Comment by Senjan21** [comment]
After a discussion within the mod team we have decided that, at the moment, we don't need such feature at the moment. Thanks for the suggestion.
