### ISSUE TITLE
Mute/tempbans, etc. durations are 1 second off in bot's messages and DMs

### ISSUE THREAD

**Issue by AFK-debug-9** [python-discord/bot#2130]
# Issue
Every mute, temp-ban or anything that has a time (when displayed) always 1 second off.
# Example
@ERROR was muted for 2 days (1 day, 23 hours).
The `(1 day, 23 hours)` isn't required 
![alt text](https://media.discordapp.net/attachments/635950537262759947/964959764486430760/unknown.png?width=234&height=17 "Example (The best I got)")

**Comment by wookie184** [comment]
I'm not sure exactly what message you're referring to there. The general form for `!mute`, `!ban`, etc is
> Applied \<action> to \<user> until \<end timestamp> (\<time remaining>)

e.g

![image](https://user-images.githubusercontent.com/22353562/164766281-b6dae9a2-50dc-49cc-b943-a9f47f01c88e.png)


This issue still applies though. A fix for this would be to use the total duration instead of the time remaining (given they should be the same when creating an infraction).

**Comment by minalike** [comment]
Even if it's technically inaccurate, I would much prefer that the bot displays the rounded duration (i.e., the duration that the moderator used in the infraction itself).

The OP may possibly be referring to the message from the bot as well.

**Comment by onerandomusername** [comment]
Why not use discord provided timestamps with the end time?

**Comment by minalike** [comment]
We already use them for <end timestamp>, so you mean for <time remaining> as well?

I feel that's less useful. In the beginning it will say "in 1 day" and then as time goes by it will say "in X hours" and then as more time goes on it will say "X [units] ago."

I like the duration being just normal static text, I just wish it reflected the actual duration written in the infraction by the moderator (or the bot), rather than a calculation of how much time is remaining (I assume that's what it currently is).

**Comment by mbaruh** [comment]
To give some context, the duration in parentheses is calculated after the infraction is added to the database. In a very rare case we had some latency and a 10 minute mute was applied 6 minutes after it was added to the database. In that case we were told the mute will last 4 minutes, which is correct.

That said, it doesn't seem like a very compelling reason to keep this behavior. I'm ok with just using the supplied duration as-is, or maybe we could add a check to make sure the delta is no greater than a few seconds to account for edge cases.

**Comment by AFK-debug-9** [comment]
![image](https://user-images.githubusercontent.com/75903679/165084404-4051131b-a919-4a6f-b8b3-5ff5f599d473.png)

**Comment by AFK-debug-9** [comment]
P.S.A I'm surprised this lasted more than 15 min

**Comment by greyblue9** [comment]
This is something I've noticed with discord relative timestamps in general. Even if you do time = 0 it will say Dec 31 1969.

**Comment by AFK-debug-9** [comment]
> This is something I've noticed with discord relative timestamps in general. Even if you do time = 0 it will say Dec 31 1969.

```py
time += 1
```
