### ISSUE TITLE
Adjust #defcon channel topic based on DEFCON status

### ISSUE THREAD

**Issue by sco1** [python-discord/bot#228]
Since it's easy to forget that DEFCON is enabled, and can be easy to miss in the general chatter of the mod logs, I'd like to suggest that the #defcon channel topic reflect the current defcon status.

Python already has channel management roles, so it's able to edit the channel topic.

**Comment by ByteCommander** [comment]
Alternatively or additionally, the defcon status could also be made temporary, similar to tempmute or tempban infractions. That would mean someone could enable it like `!defcon enable 7d` and it would disable itself automatically after that time. 

Another idea would be to regularly post reminders in #defcon (maybe once per day) while it is active, or possibly instead of deactivating itself after a temporary timeout like above is over.

**Comment by sco1** [comment]
Closed by #229 

Eventually I'll remember to use keywords in the PR
