### ISSUE TITLE
Add discoverability of keywords that point to particular rules

### ISSUE THREAD

**Issue by shtlrs** [python-discord/bot#2280]
This PR: [Add support to fetch rules via keywords](https://github.com/python-discord/bot/pull/2261) allows us now to invoke particular rules based on keywords that map to that rule.

The **problem** is that there is currently no way to discover what these keywords are other than looking at the [source code](https://github.com/shtlrs/python-discord-site/blob/7fd81a80049763f1dc71815da27d65ce4344a191/pydis_site/apps/api/views.py#L133) to look for these keywords.

So I think having a new command, whose name can be agreed upon later, that lists these keywords would be helpful.

**Notes**
* Let's call the command **rule_keywords** for now.
* Output format is just for demo purposes and will be discussed

Here's how I see this working.

1. We can fetch keywords of **one rule** on the rule number.
So for example, if I Invoke the following command `!rule 1`, and the bot sends out the rule, and if I'm curious about what could the possible keywords for that rule are, I can invoke it likewise:
`!rule_keywords 2`
This would trigger the following response
![image](https://user-images.githubusercontent.com/48383734/191117943-20e77c01-3acd-435f-8606-60587d4ef42a.png)

2. We can allow fetching keywords of **multiple rules at once** like this: `!rule 1 2 3`
The output will be the same as the previous one, only just **paginated** ( one rule per page )

3. If someone invokes it with no particular number, i guess the choice here is to either list them all or none at all

4.  I first thought of the possibility of checking whether a kw exists or not, but that's unnecessary since someone can just try invoking a rule with that keyword. So I think this **shouldn't be an option**

@wookie184, @MarkKoz  what do you think ?

**Comment by MarkKoz** [comment]
I don't feel like this feature is necessary. If it were to be added, the simplest way would be to have the same behaviour as the normal rules command, but with the added keywords in the embed. Maximise code re-use.

**Comment by shtlrs** [comment]
@MarkKoz How do you think people should discover keywords then ? 

And I don't know if you remember, but in bot pr that adds the support for keywords, the first implementation did include the keywords in each rule invocation, but we said that it'd add too much clutter so it got removed.

**Comment by MarkKoz** [comment]
I don't think discoverability is too important because the primary way to use the command is 
with rule numbers, which are already discoverable. The keyword support is there for those that happen to remember them or pick them up from seeing other users invoking the command. Furthermore, the keywords are intuitive enough that one is likely to correctly guess a keyword.

Having that info in a new command would not help discoverability much — it seems unlikely someone would figure out that command exists on their own. If anything, the best bet would be to have a list displayed in the `!help rules` output. However, I don't think it currently supports dynamically generated descriptions.

**Comment by shtlrs** [comment]
Okay, I see your point.

Then I don't quite get the whole point of adding the feature in the first place if the rules are always discoverable and displayed in !help rules.

Can you explain more what you mean by 
> However, I don't think it currently supports dynamically generated descriptions.

**Comment by MarkKoz** [comment]
> Then I don't quite get the whole point of adding the feature in the first place if the rules are always discoverable and displayed in !help rules.

Numbers are more difficult to remember than keywords. For example, I remember there is an "ad" keyword just from my quick testing session, but I still have no idea what the rule number for that is off the top of my head.

> Can you explain more what you mean by

The help command displays what's in a command's docstring. If the keywords were added to the help command output, ideally they'd be pulled from the API rather than hard-coded into the docstring, because the former would avoid redundancy and maintenance burden.

My opinion is not that the keywords shouldn't be discoverable, but rather that the proposed approach isn't as effective. The help command would be a decent spot if we could make that work dynamically without too much hassle. Still open to more suggestions of course.

**Comment by shtlrs** [comment]
@MarkKoz 

I personally don't know if it's possible to dynamically generate doc strings, but a quick search will help me find out.

So if it's indeed possible, should we try going in that direction ?

**Comment by MarkKoz** [comment]
> I personally don't know if it's possible to dynamically generate doc strings, but a quick search will help me find out.

I am not certain, but you can look into appending to the function's `__doc__` attribute. 

> So if it's indeed possible, should we try going in that direction ?

I'm fine with it. Does anyone else have objections?

**Comment by wookie184** [comment]
I'd be fine with that. I also think a static command displaying the aliases would be fine if that doesn't work, i.e. not displaying rule text or taking any arguments, just displaying all the keywords along with each rule number.

**Comment by shtlrs** [comment]
Okay, I'll start having a look.
Can someone assign this to me ?

**Comment by shtlrs** [comment]
@MarkKoz I think that changing that dynamically is going to be a PITA concerning how simple this should be.
The __doc__ dunder attribute is not writable, which throws an AttributeError upon trying to modify/write to it.

So we could go with @wookie184's approach here, and we have a static command that fetches the rules & kws & maybe even cache them per rule number ?

No need to make the http request each & every time, WDYT?

**Comment by MarkKoz** [comment]
> I think that changing that dynamically is going to be a PITA concerning how simple this should be.
The doc dunder attribute is not writable, which throws an AttributeError upon trying to modify/write to it.

Seems pretty straight forward. I don't know why you'd get an error.

```py
>>> def foo():
...     """hello world"""
>>> foo.__doc__
'hello world'
>>> foo.__doc__ = "1"
>>> foo.__doc__
'1'
>>>
```

> we have a static command that fetches the rules & kws & maybe even cache them per rule number ?

Isn't that essentially what your original suggestion was? I brought up concerns over discoverability of a separate command.

**Comment by shtlrs** [comment]
My bad, what I meant is, we have another callback that fetches & composes the rules, and then the help argument in the command decorator will take that callback.

And what I also meant is that this callback will cache the results so that we don't have to get them over & over again.
But it'll require an instance of the API client to do that, is there a global instance we could use ? (from bot core maybe ?)

What do you think ?

**Comment by MarkKoz** [comment]
> My bad, what I meant is, we have another callback that fetches & composes the rules, and then the help argument in the command decorator will take that callback.

Keep in mind discord.py expects a string value, not a function. It looks like `@command(help=myfunc())` may work since this gets executed as the cog loads, and extensions are loaded after the Bot has already been created and has an APIClient.

> But it'll require an instance of the API client to do that, is there a global instance we could use ?

Yes. The global instance is [here](https://github.com/python-discord/bot/blob/main/bot/__init__.py#L20) and it has an `api_client` attribute.

**Comment by shtlrs** [comment]
@MarkKoz @wookie184 
Here's a glimpse of the thing in its `raw` format
![image](https://user-images.githubusercontent.com/48383734/197386380-7de4bd90-67b7-4802-8040-44b4285da1db.png)

Add a bit of styling to it, and we should be ready, WDYT ?
