### ISSUE TITLE
Add a `doesntwork` or similar tag

### ISSUE THREAD

**Issue by kkrypt0nn** [python-discord/bot#2297]
People tend to just send in help channels or similar such messages
> Hey, can you help me? My code doesn't work.

Although we may have a code snippet from them, which may not be the source of the issue, there is a lot of valuable information that is lost. Useful information would contain things like
- What is the user's end goal?
- What is the current behaviour of the code? Is it working until some point or not starting at all?
- What are some solutions the user has tried?
- What is the traceback the user it getting?
- ...

Such information is lots of times critical to guide someone into fixing their issue or explain why their current code doesn't work.

I am very aware of the `!traceback` command but do not believe it does reflect exactly everything that is needed to fully help someone at the best and to prevent saying things they may have already tried

**Comment by shtlrs** [comment]
I think this would be quite similar to a recent tag we had about how to ask a question.

The problem was it became somewhat toxic and people started spamming it.

We have alot of new joiners in our community, so this is a scenario that we can expect quite often.

So it would be history repeating itself IMO.

I think it's better if we leave potential helpers ask the question themselves, it would also help us to explicitly identify people that show '' hostility '' towards beginners.

**Comment by kkrypt0nn** [comment]
Ah, haven't seen that previous tag before, hence haven't seen the effect it had.

Don't want it to get repeated and get *more* toxicity than the toxicity there already is that can't be avoided.
Will close the issue for that reason and the one you've mentioned - thanks for your input :)
