### ISSUE TITLE
Permanent roles view

### ISSUE THREAD

**Issue by mbaruh** [python-discord/bot#2332]
Our current setup is that users must run `!subscribe` in bot-commands in order to bring up a view of all self-assignable roles.

We should create a permanent view in `#roles` with a single button which will essentially run the command (with an ephemeral message).

This is more in line with how it works in other communities, with a better UI than running a command, and arguably better discoverability.

The current `!subscribe` command should remain as-is for the time being.

**Comment by shtlrs** [comment]
Can I yoink this?

**Comment by mbaruh** [comment]
Sure!

**Comment by shtlrs** [comment]
@mbaruh What do you think of redirection users to the bot-commands channel when they click on that button in the #roles channel ? 

The problem is, since we want them to be ephemeral messages, the bot won't be able to edit them whenever a user clicks on a particular role, which makes it non feasible.

I worked around this by giving the 2nd view a timeout, and it gets deleted upon timeout, and it works just fine.
The only thing that worries me is that people would spam this, which causes the #roles channel to become clattered and I don't see that as a good option.

So what I thought of, we do the same thing we do for users when they execute a command in an appropriate channel, the bot sends the response in #bot-commands & tags them there.

**Comment by mbaruh** [comment]
Ephemeral messages can be edited.

If they spam it and it becomes cluttered that's their problem, they're the only ones who will see the clutter.

**Comment by shtlrs** [comment]
Ok, I think I know what was wrong.
Ignore my last comment then, and thanks for the hint !
