### ISSUE TITLE
Only delete illegal attachments in help post, not the entire post

### ISSUE THREAD

**Issue by Simonrazer** [python-discord/bot#2377]
When creating a  Post in help and attaching a file that you dont allow, PLEASE not delete the post after one sends it.
Typing out good questions AGAIN cause you deleted it because of smth I couldnt know is not cool

Discord msg about that:
![image](https://user-images.githubusercontent.com/30187223/211022319-b52b8215-4556-46f1-93cd-f73a42f8d2a7.png)

**Comment by ChrisLovering** [comment]
This isn't possible as Discord only allows users to edit their own messages, not the messages of others.

We are working on a new filters system, which will include the ability to DM users with the content of the message that was deleted.

So that actual problem of not being able to access the message you pasted will be solved by https://github.com/python-discord/bot/issues/1530
