### ISSUE TITLE
Reply to !eval message instead of pinging

### ISSUE THREAD

**Issue by Robin5605** [python-discord/bot#2382]
It was discussed in [#community-meta](https://discord.com/channels/267624335836053506/429409067623251969/1064000890798870558) if the `!eval` command should reply to the original command instead of sending a separate message with a ping. Thoughts on this? I'd be willing to PR if accepted.

**Comment by wookie184** [comment]
Sounds good to me, I don't see why not.

**Comment by TizzySaurus** [comment]
What would happen when the issue invokes the command in a non-whitelisted channel? I suppose it'd have to still send a new message that pings in bot-commands?

Also would the reply be ephemeral? We presumably don't want that, since a lot of the time the eval command is used to showcase something, meaning other people need to see the outcome.

And I believe @bj0key, the user who raised this, said they'd like to implement this fwiw @Robin5605/

**Comment by ionite34** [comment]
Yeah this seems good. Sometimes the eval takes a while and returns a few messages after the original `!eval`, so it's unclear which eval resulted in the output, the reply would provide a clickable link.

**Comment by bj0key** [comment]
Yeah, I wouldn't mind implementing this. I think it'd also be worth having `!timeit` also reply on response, for the sake of parity between the two evaluation-based commands.

**Comment by e1pupper** [comment]
I can take on this!

**Comment by mbaruh** [comment]
Sorry for not noticing your message earlier @bj0key, I assigned it to someone else, hope you don't mind.
