### ISSUE TITLE
Only let the invoking user delete module not found error messages

### ISSUE THREAD

**Issue by n0Oo0Oo0b** [python-discord/bot#2407]
When `!pypi` is unable to find a package, an error is sent like so:
![Screenshot_2023-02-15-17-48-50-75_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/84215197/218993331-9d0fc6bb-60f4-43e6-b2c6-33d45301bf73.jpg)
However, the trashcan reaction can be used by anyone to delete the message. This can be problematic as it can be intentional to show that a package with that name doesn't exist. I propose that only the user that invoked the command will be able to delete the error message. This will also make the behavior more consistent with other delete functionalities like `!eval`.

**Comment by wookie184** [comment]
As far as I can tell only the invoker and moderators should be able to delete it. It will however always auto-delete after a delay to clean up the channel.

This isn't done with `eval` because a error is a valid result. We could change it for pypi, but I think most errors would probably be because of a mistake by the person running the command.

**Comment by wookie184** [comment]
Closing this as I don't think there's anything that should be changed.
