### ISSUE TITLE
Optional DEFCON expiration specification

### ISSUE THREAD

**Issue by sco1** [python-discord/bot#248]
Reposting Byte's suggestion from #228:

> Alternatively or additionally, the defcon status could also be made temporary, similar to tempmute or tempban infractions. That would mean someone could enable it like `!defcon enable 7d` and it would disable itself automatically after that time.

**Comment by SebastiaanZ** [comment]
What's the current criterion to disable defcon? Is it based on something like reviewing the logs or a feeling of "Oh, it's been on for a while, let's disable it"?

Regardless, I think adding such a time-out would be great since the current implementation still relies on "human memory" to check the channel status. I think there are two options:

- A "hard" timeout with the bot disabling defcon automatically when it runs out
- A "soft" timeout with the bot mentioning @admin to get someone to review defcon status.

A timeout-less option would be having the bot post a status update every day to the defcon-channel while it's on to remind people it's still on. It could include some useful information, like the number of users defcon has prevented from joining since turning defcon on/the previous status update.
