### ISSUE TITLE
`/tag` command output bugs

### ISSUE THREAD

**Issue by TizzySaurus** [python-discord/bot#2583]
When executing the command `/tag` without any arguments, a list of all tags is displayed. However, for some reason there's a random bullet point at the top of the list:
<img width="409" alt="Screenshot 2023-05-07 at 14 04 15" src="https://user-images.githubusercontent.com/47674925/236679499-6d749c3d-12c0-4142-b5c5-7d865214a4b0.png">

Similarly, when the "Did you mean" message comes up for a non-exact multi-match, such as `/tag name:f-str`, the "Did you mean ..." has a space before the `...` that shouldn't be there:
<img width="263" alt="Screenshot 2023-05-07 at 14 13 53" src="https://user-images.githubusercontent.com/47674925/236679711-4a55c450-fd2d-4765-8ae5-af8098ca955b.png">

The relevant lines of code appear to be [here](https://github.com/python-discord/bot/blob/main/bot/exts/info/tags.py#L267) and [here](https://github.com/python-discord/bot/blob/main/bot/exts/info/tags.py#L237), although I've not delved too deeply into the code so this could be wrong.

**Comment by wookie184** [comment]
It's because of tag groups, https://github.com/python-discord/bot/issues/1545, we don't have any tag groups yet, so all tags are under the default group which has no name, hence is just a bullet point. Related: https://github.com/python-discord/bot/issues/2423

**Comment by tarunsamanta2k20** [comment]
I would like to work on this issue.

**Comment by RohanJnr** [comment]
@tarunsamanta2k20 hey, are you stilling working on this ?

**Comment by RohanJnr** [comment]
These are some of changes we should be doing:
- Change the tag embed footer to remove prefix and use /
![image](https://github.com/python-discord/bot/assets/37217450/28783a0b-8115-4fad-830c-8ddada6bfc72)

- We need better help message to tell users on how to use tags from a group. Currently, the syntax to view a tag from a group is `/tag name:<group_name> <tag_name>`, this has to be mentioned in the tag help message.

**Comment by hedyhli** [comment]
An update on the points proposed in the issue:

- [x] Empty bullet (#3011)
- [x] "Did you mean ..." (#3011)
- [x] Tag embed footer (#2987)
- [ ] Extra aliases in tag suggestions

@RohanJnr, regarding improving the docs for `/tag` -- although we don't actually have any tag groups yet, I agree it could perhaps be made clearer. I've opened a separate issue for it since this is unrelated to the `/tag` output in this issue. (#3014)

Now it looks like the aliases cluttering already have an issue of its own: #2345. So I'll close this issue since everything mentioned has been addressed.
