### ISSUE TITLE
Make `resources` a slash command.

### ISSUE THREAD

**Issue by shtlrs** [python-discord/bot#2889]
Currently, the `resources` command allows to fetch certain resources with a specific topic.

The catch is: You need to know the different topics that we have.

This can be made easier by switching to a `Slash command` that allows `auto completion` whenever we input text.

**Requirements**
We'll need to expose an api that allows to fetch the resources and **cache** them, as they're not that prone to change.

If indeed we introduce a new resource to `site`, we can have a  `reload` subcommand to reload the resources from the `api` (which we'll restrict to particular roles/users)

**Comment by wookie184** [comment]
If you look through the uses of the `!resources` command, it's very often used as a reply to someone, which is useful, especially in busy channels like `#python-discussion` where it wouldn't be obvious otherwise. Switching to a slash command would make this not work any more.

Using the topic arguments is less common and useful in less cases, since it's usually good enough to link someone to the overall page and let them decide what specifically they want to look for, so I don't think it's worth the worse user experience in other cases.

I also personally think slash commands are more clunky in general, for example if someone just wanted a message after the resources command like `!resources Take a look at these resources` then the UX with slash commands would be worse.

**Comment by shtlrs** [comment]
Now that I've read what you've said, I agree with you.

I'll close this then, thanks!
