### ISSUE TITLE
minor !nominate improvements

### ISSUE THREAD

**Issue by heavysaturn** [python-discord/bot#290]
* When a user is nominated multiple times, it would be great if this showed in the #talent-pool embed. Something like "Nominated by: Scragly, lemon, fiskenslakt" would make it clear that the user had been nominated multiple times, which should count for something. The reason should not change, but a note should be added.

* It should not be possible to nominate someone who is already a Helper, Mod, Admin or Owner.

* The notes that are added currently are prefixed with `bb watch`. Perhaps for nominations, these could be prefixed with `Helper nomination:` or something.

**Comment by SebastiaanZ** [comment]
> - When a user is nominated multiple times, it would be great if this showed in the #talent-pool embed. Something like "Nominated by: Scragly, lemon, fiskenslakt" would make it clear that the user had been nominated multiple times, which should count for something. The reason should not change, but a note should be added.

Okay, I would like some input on this. since there are some advantages and disadvantages to all solutions I've thought of. Not all of them implement all of the ideas expressed here.

First of all, I'm going to assume that for the moment, we'd like to not to change the underlying API. We may want to think about changing it in the future, after the Django is completed, but if we do, my recommendation would be to consider separating the infraction/user record API from the watch API. (Don't know if that's desirable, but instead of incrementally 'hacking' additional stuff on top of the old one, we may want to do a proper evaluation of it.) So, all of the assumptions below are with the current API in mind.

1. The easiest option, by far, is silently ignoring additional nominations while a user has a current nomination. It's a simple check, but we'll lose information, as the additional/secondary nominations are not stored. I'd say that's not what we want.

2. Storing the additional nominations as notes as if they were the first nomination, but selecting *oldest* instead of the newest nomination as the primary one to display the correct timing and reason. The advantage is that this implementation is straightforward and we store everything we want to store, but is also has one **major** drawback: It introduces a new bug, namely that if someone has more than one separate nomination periods*, the embed will always display the information of the earliest period.

*) A plausible reason this may happen is someone is nominated, but disappears from the server for a while, triggering us to remove them from consideration. After a while they return and show consistent activity, so we decide to nominate them again to observe them for a while.

3. Storing additional nominations as described in point 2, but altering the prefix compared to the initial/primary nomination. For instance, if someone does not have an active nomination, use the prefix `Helper nomination:` in the note; if someone does have an active nomination use something like `Additional nomination` or `Helper nomination (additional)"` as a prefix in the note. That way, we can always locate the latest "primary" nomination event and we can then work-out with additional nominations belong to it, as they come after it, date-wise.

A downside of doing that is that we're basically storing even more information in a single field: that it's a nomination; whether it's the initial or an additional nomination; and the actual reason itself. That's quite a hacky way of storing information in the database and we should probably split it up into separate fields (That way we can also create a view that allows us to directly query the relevant information instead of using queries with regex searches in fields).

Still, with the last option, we will be able to do what we want. (Store all the information and display it correctly.)

**Comment by gdude2002** [comment]
Is changing the API such a bad thing? Django isn't in prod yet (right?) and the old API will be replaced by that at some point anyway.

Just gotta make sure the PRs are merged together.

**Comment by heavysaturn** [comment]
Django is getting closer to prod every day, and any work put into the flask API adds additional workload to the django branch. It's not ideal to do that at this point.

I think **3** seems like a fairly decent solution. `Additional nomination` seems to make the infraction history more readable anyway.

**Comment by SebastiaanZ** [comment]
One other minor thing, but I'll edit the current reasons of the nominated helpers manually to change the prefix. I don't think it's worth it to have fallback code to support backwards compatibility for the old prefix `bb watch` for the very few nominees we currently have.

**Comment by sco1** [comment]
Option 3 seems fine

I'm going to give a huge +1 to separating out nominations from infractions in the Django API. While this is functional in the short term, continuing to struggle against an API endpoint that wasn't designed for this is generating a lot of hacky solutions and cruft in the infractions DB.

**Comment by heavysaturn** [comment]
yeah @sco1, I agree. we should see about that in the near future.
