### ISSUE TITLE
Source command.

### ISSUE THREAD

**Issue by scragly** [python-discord/bot#331]
A source command has been discussed as a good addition in the past for the bot, with the following features:
- `!source` shows the base github repository link
- `!source <command>` will provide a github link to the relevant module:line_number directly

Feel free to recommend any additional suggestions in the comments below.

**Comment by fiskenslakt** [comment]
Not sure if someone else brought this command up, but I did mention to lemon that I was interested in writing this (However if someone wants to beat me to it, that's ok).

I got the idea from this: https://github.com/Rapptz/RoboDanny/blob/rewrite/cogs/meta.py#L163-L191

I've already started to test out the same method used above, but it doesn't work perfectly with our bot. Because of some redirection decorators and such, `bot.get_command` gets confused and returns code from the decorator instead of the cog being decorated. More testing is needed.

**Comment by scragly** [comment]
Nobody has reserved it so you're welcome to keep working on it if you want, just hold up on a PR until we have moved to Django and tested it on it. 

Sounds like you've got a good head start :)

**Comment by MarkKoz** [comment]
@fiskenslakt I think it's fine for you to assign yourself to this issue.

**Comment by fiskenslakt** [comment]
@scragly right yea, was definitely gonna wait till after the feature freeze.

@MarkKoz I don't think I *can* assign myself the issue lol

**Comment by MarkKoz** [comment]
Strange. I can assign myself and a bunch of others, but your name doesn't show up there.

**Comment by scragly** [comment]
Good enough. It's likely because of access levels and that he hasn't contributed to this repository yet.

**Comment by fiskenslakt** [comment]
Maybe you need to be on the contributors team? Not sure

**Comment by fiskenslakt** [comment]
@scragly Does my PR for the `!free` command not count as a contribution to this repo?

**Comment by scragly** [comment]
That's on bot.

**Comment by RohanJnr** [comment]
can i work on this?

**Comment by RohanJnr** [comment]
gonna work on this

**Comment by RohanJnr** [comment]
btw can i have some more details on this, what can the commands be?

**Comment by MarkKoz** [comment]
No progress in 4-5 months; unassigning. This is now open for anyone to work on.
