### ISSUE TITLE
Improve DEFCON direct message

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/bot#353]
Currently the DM we send to users who are rejected by defcon gives away exactly how and why we are rejecting the user. It would probably serve us better to be a little bit less forthcoming with the precise details.

Rather than saying "you can't join because your account is too new", we could simply say that their account has been identified as a potential attacker or ban evader, and that we are rejecting their access to the server. If they believe this was in error, they should try again in a few days.

**Comment by SebastiaanZ** [comment]
Let's play the devil's advocate: How is this going to sound to an innocent user trying to join the server? It's not very welcoming to hear that "you've been identified as a potential attacker or ban evader" and therefore rejected as a member of our community when you are in fact not one of those two. 

So, instead of focusing *only* on the rotten apples, we should also take the perspective of the innocent user trying to join into account. In fact, I think that's important consideration to make when drafting this message.

Now, I know, I should come up with an alternative phrasing when I criticize yours, but I don't have one at the moment. However, I am going to think about it. And, maybe, your proposed message is already the best we can come up with and/or others don't agree with my concerns.

**Comment by kosayoda** [comment]
"Hi <user> - Thanks for showing interest in the server! Your account has been denied access to our community at this time due to not having one or more required credentials. If you believe this to be an error, please try again in a few days. Thank you for your patience and we hope to see you soon!"

How’s this sound?
