### ISSUE TITLE
Add Loose Resource Files for Tags

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/bot#388]
Actioning python-discord/organisation#117. 

The files could just be markdown but if we want more customisability of embeds we can use a format like JSON and feed it into [`discord.Embed.from_dict`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Embed.from_dict). 

We'd need to keep in mind that Discord only supports a subset of markdown so a GitHub render of a markdown file will not necessarily be representative of how it'll appear on Discord. [Embed Visualizer](https://leovoel.github.io/embed-visualizer/) can be used for previewing tags.

The existing tags will need to be imported into this new format from our database.

**Comment by scragly** [comment]
Tags are now part of the site API, and are editible by mods+ in the admin panel.

For now, we've added a tag directory with tag contents in individual markdown files within the meta repository:
https://github.com/python-discord/meta/tree/master/tags

For now, it's a manual process of adding or editing tags via bot or site admin whenever we get a PR merged in, however in the future this could possibly be more automated.

Due to the change in situation, I'll close this ticket.

**Comment by MarkKoz** [comment]
It was decided in a meeting that we want to go with this approach.
Therefore, I think that if this is going to be closed, there should be a
consensus to reverse the decision to do this. And, to be clear, when this
was decided, the tags view already existed on the API.

Den fre 15 nov. 2019 06:28scragly <notifications@github.com> skrev:

**Comment by scragly** [comment]
Very well, I'll open an org issue for it to be discussed in the next staff meeting.

**Comment by MarkKoz** [comment]
Closing in favour of lucky number #777
