### ISSUE TITLE
Using a webhook for the Reddit post relay

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/bot#391]
We're currently relaying the new Reddit posts (and the weekly top posts overview) as regular messages to a text channel. Since the subreddit sees frequent activity, I propose to change this to a method that uses a webhook to post the messages to the channel. 

This has two advantages:

1. Webhooks use a different rate limit pool than regular messages;
2. We can use a stylized author icon and display_name

The latter is not really important, but will look nice; the former is the biggest advantage of this change.

This should not be difficult to implement, although an admin+ needs to create the proper webhook for the relevant channel.

**Comment by mathsman5133** [comment]
I could work on this. 

I also believe the auto posters could utilise `discord.ext.tasks` extension for cleanness of code, and to resolve issues such as #360/#361

**Comment by lemonsaurus** [comment]
@mathsman5133 you _could_ work on this or you _are going to_ work on this? it's yours if you want it.

If you're doing this, I have one more request for this cog, which came up in the last staff meeting. Instead of relaying every post that is posted on `/r/python`, it would be nice if it just posted the top 3 posts that day, once every day. Currently, the channel is very noisy and I doubt anyone really uses it for anything except the weekly top 3 in the pins.

**Comment by mathsman5133** [comment]
I will work on this, please :)

The weekly is currently top 5 - just making sure you want the daily to be top 3? Also, is there a specific time every day - and/or do you want to make this configurable?
