### ISSUE TITLE
ExpirationDate Converter Not Correctly Parsing Duration Directives

### ISSUE THREAD

**Issue by sco1** [python-discord/bot#446]
`dateparser`'s date parsing is not correctly parsing our expiration duration directives per what's expected by http://strftime.org/:

![image](https://user-images.githubusercontent.com/5323929/65425362-c7224900-dddb-11e9-8fac-e6611ed81b85.png)

From limited testing, `m` and `M` are both parsed as minutes and `y` is not correctly parsed as year. Shorter duration directives (e.g. `h`/`H` and `d`/`D`) are parsed as "expected" (but not case sensitive).

This behavior is consistent across dateparser `0.7.0` (2018-02-08), `0.7.1` (2019-02-12), and `0.7.2` (2019-09-17) so I don't think it's a new issue, just one that we might not have noticed.

**Comment by SebastiaanZ** [comment]
The tests @jchristgit has written for the `ExpirationDate` make me thing that it's meant to be used on ISO datetime strings like they are returned by our API:

```py
@pytest.mark.parametrize(
    ('value', 'expected'),
    (
        # sorry aliens
        ('2199-01-01T00:00:00', datetime(2199, 1, 1)),
    )
)
def test_expiration_date_converter_for_valid(value: str, expected: datetime):
    converter = ExpirationDate()
    assert asyncio.run(converter.convert(None, value)) == expected
```
With `'2199-01-01T00:00:00'` being one of those typical datetime strings our API returns.

Yet, we apply the converter to duration strings, like `"1H"` and `"1Y"`, directly in the command:

```py
    async def tempmute(self, ctx: Context, user: Member, duration: ExpirationDate, *, reason: str = None) -> None:
```

That makes me thing there's a mismatch between what the converter actually does and what we assume it does in the command signature. This makes sense, since previously (flask), we parsed the expiration date returned by the API to know when to schedule an expiration in the scheduler. It seems like the converter was written for that, but now applied to something different.
