### ISSUE TITLE
Nickname Changes Not Consistently Logged to #user-log

### ISSUE THREAD

**Issue by sco1** [python-discord/bot#489]
We noticed this morning that not all user update events are being logged to the #user-log channel for a currently unknown reason.

@SebastiaanZ indicated that he was going to take a look and see if some of the recent changes affected the logging logic.

**Comment by SebastiaanZ** [comment]
I've managed to trace the problem to users setting a nickname if they had none or resetting their nickname to their username (i.e., removing their server-specific nickname). What happens is that when people remove or add a nickname, the `old_value` or `new_value` is `None`.

For instance, resetting a nickname results in the following data:
```py
'nick': {
    'old_type': <class 'str'>,
    'new_type': <class 'NoneType'>,
    'old_value': 'Nickname',
    'new_value': None
}
```

Since we only record a change if both the old value and new value are "truthy", we do not record a change when this happens:

```py
                new = value.get("new_value")
                old = value.get("old_value")

                if new and old:
                    changes.append(f"**{key.title()}:** `{old}` **->** `{new}`")
```

Effectively, it means that only changes to a username or changes to a nickname show up, not changes that set or remove a nickname.

I think that instead of recording nickname changes, it would be better to record changes in the `display_name` of the member, since that is ultimately what's relevant to us. In addition, we could continue to track username changes as well, since it's valuable to track those regardless of whether the username is also the current `display_name`.
