### ISSUE TITLE
updating/upgrading contributing bot tutorial

### ISSUE THREAD

**Issue by kraktus** [python-discord/bot#496]
Not sure if it the right place, but:

This page: https://pythondiscord.com/pages/contributing/bot/ could be better (although it is already pretty good)

Rename `#bot-commands`and `#ot-offtopics` to `bot` and `off-topic-0` to actually meet with their names in `config.yml`. Explicit more that the `bot_token` has to be put in the `.env`file.

Precise somewhere that not all cogs are loaded in `DEBUG` mode, I lost one hour trying to figure why `verification.py` was not loading.

What do you think?

**Comment by lemonsaurus** [comment]
I appreciate the feedback, these are good suggestions. I would suggest we make the following changes:

* Let's change the names of the channels in `default-config.yml` to actually match the channel name. It should be called `bot-commands`, not just `bot`.
* Let's change the guide so that we create all three off-topic channels, and simply name them #off-topic-0, #off-topic-1 and #off-topic-2 to match the constants.
* I'm gonna discuss with the core devs whether perhaps we should just load all cogs in debug mode from now on. The reason they're not being loaded is because we used to test the bot on the main server, but recently we've been using a test server for this instead and I kind of think that's a better system.

**Comment by kraktus** [comment]
Yes I think loading all modules is a good idea, but then a `#verification`(and precise it is not the same as `#checkpoint-test` in `config.yml`) channel would have to be include in the tutorial. I could do the changes myself but I can't find the source code of the page.

**Comment by scragly** [comment]
The config alterations can be done at the same time as #206 is addressed.

**Comment by MarkKoz** [comment]
Because both this and #206 are stale, I'm just going to go ahead and rename the constant now.
