### ISSUE TITLE
`!whitelist` command to whitelist stuff from our filters.

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/bot#639]
The bot should be able to whitelist stuff from our filters with a command.

This should probably be a command group that allows whitelisting of several different things that we're currently configuring in default-config.yml.

- `!whitelist guild 15409531` should whitelist a guild invite for posting on our server. Currently this is managed in the `guild_invite_whitelist` section in default-config.yml
- `!whitelist format .ipybn` should whitelist a format from the anti-malware filter. Currently managed in the `anti_malware.whitelist` section of the `default-config.yml`

This issue will require a corresponding change to the `site`. You can find the corresponding issue for this at https://github.com/python-discord/site/issues/305

**Comment by atmishra** [comment]
Can I work on this?

**Comment by lemonsaurus** [comment]
@atmishra yes, as long as you're comfortable working on both sides of the stack. This will require a change on the `site` as well.

**Comment by atmishra** [comment]
Thanks, @lemonsaurus for assigning this to me. I am more comfortable with the site part of this task So it will not be a problem for me. On the command part, can you give me some more details like:

- What all items can be added to this whitelist?
- Should it also give option to list, edit or delete the whitelist?
- any restrictions on who can call this command or in which channels?

This is my first task on creating a command, So need some more clarity. Thanks!

**Comment by SebastiaanZ** [comment]
> - any restrictions on who can call this command or in which channels?

It should definitely be restricted. I think this falls under the umbrella of server administration, so it would make sense to restrict this to those with the admins or owners role. There are constants defined in `config-default.yml`/`bot.constants` with the relevant role IDs. It's not really sensitive information, so I don't think a channel lock-down is necessary to prevent accidental data leaks.

> - Should it also give option to list, edit or delete the whitelist?

Definitely, with the listing preferably separated by the type of whitelist (guild invite, file extension, ...). I'm not sure if an `edit` makes sense; I think the whitelist mutations will mainly come down to either adding an item to the whitelist or removing it, but feel free to play around with to see if it makes sense from a UX point of view. Maybe someone else has an opinion about this as well.

> - What all items can be added to this whitelist?

This is the most difficult question to answer. So far, we've mainly discussed the whitelist in relation to the server invite filter and the file extension filter. In general, I think the back-end solution should be flexible enough so that adding more whitelists in the future isn't difficult. 

The other two whitelists that are currently in there, the `channel_whitelist` and `role_whitelist`, are fairly static and depend on other constants with pointers/references. I don't think it's necessary to include those, but we can always add them later if we want a single, tried and tested method for whitelists.

**Comment by lemonsaurus** [comment]
@atmishra The site-side changes seem to be done, but we still need the bot-side changes to be made. Are you still interested in tackling this part? If so, when do you think you'll be able to open a pull request for it?

I don't want to merge the site-side changes until the bot changes are ready, since that might require us to write another migration for site for any changes made to the whitelists in the space between now and then. It would be better to merge both of these at the same time.

**Comment by atmishra** [comment]
@lemonsaurus Thanks for the feeback. I am done with the most of the work on bot side as well. I will soon raise a PR for that.

**Comment by MarkKoz** [comment]
@atmishra Any updates on your progress?

**Comment by atmishra** [comment]
Hi @MarkKoz I have raised a PR for this.

**Comment by lemonsaurus** [comment]
I'll handle this.
