### ISSUE TITLE
Remove arguments from !free command 

### ISSUE THREAD

**Issue by Akarys42** [python-discord/bot#652]
The [`!free` command](https://github.com/python-discord/bot/blob/master/bot/cogs/free.py) doesn't ping the user because the ping is inside the embed. The mention needs to be moved outside of the embed if it's to be used. 

After discussion, instead the arguments for the command and the `Hey @blah` line is to be removed.

**Comment by SebastiaanZ** [comment]
Is it meant to ping the user? It's often already invoked with a user mention, so that may lead to double pings being issued.

**Comment by Akarys42** [comment]
Looks like it is supposed to ping, see this test:

![Screenshot_20191106-171630](https://user-images.githubusercontent.com/44778521/68316214-5dbf7680-00b9-11ea-8aa3-6711fc300ba5.png)

I think the sentence `hey @user!` was meant to ping the user.

**Comment by SebastiaanZ** [comment]
It's just a common style we have to refer to a user in embeds, since it leads to a clickable mention that does not actually ping the user. I'm not sure if you can infer the intention from it that you do. I'm not saying that it wouldn't be an option to include it, but I don't think this is an actual bug; it could just be an enhancement.

I think it was left out because the most common way of doing this is `!free <mention>` instead of `!free <id>`.

**Comment by SebastiaanZ** [comment]
I can't find a consideration for this in the original PR, so I don't know. We should probably discuss if we want this change.

**Comment by fiskenslakt** [comment]
As the original author of this command, I suppose I should speak on this. @SebastiaanZ is correct, I specifically intended that the bot response **not** ping the user. Not only does this prevent a double ping with very little effort, but I did not want the bot to ping the user from the invocation of a different user. It is rare for non-staff to ever provide the ID of a user as the argument to a command. While the parsing of the user argument is flexible enough to accept an ID, I intended for people to provide a user mention as the argument.

To be honest however, providing any arguments to this command is exceedingly rare, and I only really provided it in the first place because I like having options. When I first wrote this command, I couldn't have possibly imagined how it would be used by our users. If you spend any time in `#bot-commands`, you'll know that it is almost entirely used by users checking help channel availability on their own, rather than to suggest an available help channel to a user who has posted in an ongoing help session.

**Comment by fiskenslakt** [comment]
In fact, ever since the output of the command was redesigned, I think even the `Hey <user>` part is completely unnecessary and should've been removed as well.

Now that we have a good idea of how this command is used, I think the `!free` command should no longer take any arguments. The `seek` argument is never used, and if the command no longer takes arguments, nothing is stopping users from providing a user mention after the `!free` invocation.

**Comment by lemonsaurus** [comment]
We will be removing `!free` in https://github.com/python-discord/bot/pull/786, so this is no longer relevant.
