### ISSUE TITLE
!hush command

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/bot#661]
Occasionally, two users will be too busy fighting each other to notice a moderator trying to step in and clean up the situation. In these cases, we want to be able to silence the channel for a few minutes while we sort out what's going on and what we're going to do about it.

Enter: `!hush`. This command will remove the ability for anyone except staff to post messages in that channel for a short duration, 10 minutes by default.

This will not need any work on the `site`, so it should be quite approachable.

Since this is a moderator command, [you should write unit tests for it.](https://github.com/python-discord/bot/blob/master/tests/README.md)

## Implementation details:

- [ ] `!hush` should remove posting permissions for non-staff in the channel it is called in for 10 minutes.
- [ ] Add the alias `!silence`
- [ ] `!hush <duration>` should set a custom duration. This duration can either be specified as `5M`, `5m` or just `5`. It should not be possible to exceed 15 minutes in duration.
- [ ] A special alias `!shh` should be added. This alias should be handled by the CommandNotFound handler (the way we do tags aliasing today). That's because we want to be able to support a dynamic amount of `h`'s behind the `sh`. For each `h`, increase the duration by 2 minutes. For example, `!shh` would cause a 4 minute hush, `!shhh` would cause a 6 minute hush, `!shhhh` would cause an 8 minute hush, and so on.  The duration should never exceeed 15 minutes, no matter how many h's you add. The minimum number of `h`'s should be 2.
- [ ] A second command, `!unhush`, should undo the hush immediately. This is important in case the bot restarts in the middle of the duration, since we're not persisting the duration anywhere.
- [ ] The unhush should also have an `!unsilence` alias, and an `!unshhh` with any number of h's.
- [ ] Both commands should have unit tests.

**Comment by fiskenslakt** [comment]
While I love the idea of the dynamic amount of `h`'s idea, I really don't see the point in having a duration for this. Are we assuming that the invoker will forget to unmute the channel? This should absolutely just be a toggle in my opinion. Mute and unmute, that is all.

My rationale for this is two-fold:
1. Duration often causes command misfires due to typing it incorrectly. And given this command is often one that would need to be invoked quickly, pausing to think about a duration is just a waste of time, even if the time wasted is fairly small. Having a duration also makes the command more complicated, and will likely cause some staff to forget how it works, and thus waste time checking the command's help page to see the syntax.
2. There are situations in which a longer duration would be wanted. For example, whenever a regular user manages to slip through the cracks and mention a role that pings a ton of users, and causes absolute chaos in that channel for a seemingly endless amount of time. Ergo, it would be better to just not worry about the duration at the time of invocation, and just feel out when a staff member should unmute the channel again.

If we really feel there is a chance that staff will forget to unmute a channel, I'd prefer to have the bot ping us in `#mod-alerts` every 15min or so reminding us which channels are currently muted. It would also be nice to have some sort of status command telling us which channels are currently muted, despite it likely not getting much use.

Just my 2¢

**Comment by ikuyarihS** [comment]
I think defaulting to 15m if not passing in duration is a fine idea as well, but having duration will let mods be more flexible in more cases. 

I would certainly don't want to see a channel being locked up longer than necessary when there are a lot of people asking.

An example would be like this - After I muted the channel for 5m as a clear sign that the conversation is to be dropped off, if I still see wrong behaviors then I'll issue mute directly and for much longer duration. In that case, locking the channel for extra 10m may do us more harm than good, and since it's not hard to implement, I think we can go for it.

Also I second the idea of pinging periodically when somehow the channel is still locked.

#### Question about designing
Should we mute all non-mods or should we mute based on a list of roles? The former is too strict while the latter requires maintenance for the roles can change.
Or, should we mute all role that does not have admin?

**Comment by lemonsaurus** [comment]
@fiskenslakt 
> Duration often causes command misfires due to typing it incorrectly. 
> ...
> Having a duration also makes the command more complicated, and will likely cause some staff to forget how it works
The duration is optional and I think the default of 10 minutes is reasonable enough that it would be very rare to need to specify a duration at all. And when you do need to, the syntax is so simple (`!hush 5` for 5 minutes) that I'm not sure I buy that people would forget it if they had ever used it before. And frankly, I'll never not use `!shhhhh`, it's the greatest alias idea of all time.

> There are situations in which a longer duration would be wanted. For example, whenever a regular user manages to slip through the cracks and mention a role that pings a ton of users, and causes absolute chaos in that channel for a seemingly endless amount of time.
I do buy this. It might be useful to be able to toggle this on without a duration. I'm not sold on this exclusively being a toggle, but I'd be open to having the option to just toggle it on.

Maybe something like `!permahush` or `!hush forever` would be a way to achieve this. Would love to hear thoughts on this from others.

>  I'd prefer to have the bot ping us in #mod-alerts every 15min or so reminding us which channels are currently muted.

This sounds good. If a channel is muted more than 15 minutes, it can ping every 15 minutes. That is, if we allow channel mutes to exceed 15 with a permahush type feature.


@ikuyarihS 
> Should we mute all non-mods or should we mute based on a list of roles? The former is too strict while the latter requires maintenance for the roles can change. Or, should we mute all role that does not have admin?
All non-staff. Anything below Helper.

**Comment by scragly** [comment]
> I think the default of 10 minutes is reasonable enough that it would be very rare to need to specify a duration at all

Agree

> `!hush forever`

I like this option, as it sticks to the idea of having a duration as the argument still, so it doesn't introduce just another thing to remember (unlike `!permahush`)

> ping us in #mod-alerts every 15min or so reminding us 

Agree

**Comment by Numerlor** [comment]
Can start working on this, but may take longer as I'll be fresh to tests in general

**Comment by SebastiaanZ** [comment]
That's okay, there's no rush. Keep in mind that the pending PR to upgrade our bot to Python 3.8 (#783) will bring some changes to our test suite.

**Comment by Numerlor** [comment]
Does pinging mods and setting up the 15 minute alerts sound good when the bot restarts with active hushed channels?

**Comment by lemonsaurus** [comment]
@Numerlor

How are you planning to detect that there are active hushed channels on restart? It does sound like a good solution to just setup the mod ping cycle, though, yes.

I don't think we need to take channel as an arg for any of these commands. This command should only be invoked in the channel we are currently in.

I'm not sure what you're asking about regarding keeping remaining durations. are you suggesting some sort of storage for these things? I was hoping to keep this command as simple as we can, without need for persistant data.

**Comment by Numerlor** [comment]
> @Numerlor
> 
> How are you planning to detect that there are active hushed channels on restart? It does sound like a good solution to just setup the mod ping cycle, though, yes.
> 
> I don't think we need to take channel as an arg for any of these commands. This command should only be invoked in the channel we are currently in.
> 
> I'm not sure what you're asking about regarding keeping remaining durations. are you suggesting some sort of storage for these things? I was hoping to keep this command as simple as we can, without need for persistant data.

We can loop over channels from `bot.get_all_channels` and check their permission overwrites to get the currently hushed channels on startup.
I set up the commands to take a(n optional) channel arg in #812 should that be removed to keep it simple?
Probably overthinking it with the timeouts as it won't have a lot of overlap or special situations but was thinking about keeping a dict with the end times in it to see how much is remaining in some sort of a list command.

**Comment by lemonsaurus** [comment]
personally I think both listing commands and optional channel selection are probably overkill, but maybe someone else can give their opinion too.

I also am not sure how you plan to differentiate between staff channels and hushed channels, since just developers not having speaking permissions is not a very unusual configuration.

**Comment by Numerlor** [comment]
Ah right, I kinda mixed up some permission things in my mind. Could be done by checking read permissions (if the public channels are set up in a way that makes it easy or are then removed) but it indeed looks a bit overkill there with the list with the above logic being required behind it

**Comment by lemonsaurus** [comment]
some channels even have read but not write permissions by default, like announcements and devlog. and I don't wanna be adding lots of exceptions to some list.

The only way I can think of for a restarted bot to discover hushed channels would be if we somehow marked these channels

**Comment by Numerlor** [comment]
After some discussion in #dev-contrib I'll be removing the channel params.

Without adding any persistence to the channels or changing their structure
to be able to discover hushed at runtime, we can do an alert with hushed
channels on cog unload.
Only sure thing without persisting it externally is potential loss of a
permissions state for send messages, for an unhush it can only be either
set to allowed or the inherited without knowing what it was on previously,
if that's a concern.

Do we care that for example a mod channel could be potentially unhushed?
The current check I have implemented is only for making sure the perms are
already not set to allowed.
Could also expand the check to the inherited if they're set up where that'd
make a difference, or make sure the channel is not in `STAFF_CHANNELS` from
constants.

>

**Comment by lemonsaurus** [comment]
removing channel args sounds good.

Throwing a warning on cog unload for active hushed channels is a bit of an edge case but nice to have. most of the time the docker containers shutdown probably will not be graceful enough to allow that to trigger (I might be wrong about this), and so it will only work for !cog unload, which is rarely used.

beyond that I don't see the need for any of the extras you mention. it doesn't matter that staff channels are hushable - it might actually be nice for testing purposes.
