### ISSUE TITLE
Relay all bot DM's to log channel

### ISSUE THREAD

**Issue by fiskenslakt** [python-discord/bot#667]
# Abstract

Currently we're only able to read messages that were sent as a DM to our bot that trip our filters. We should relay **all** messages that are sent to the bot, and who sent it.

Depends on [#174](https://github.com/python-discord/organisation/issues/174) being actioned.

# Specification

This should probably be discussed, but I propose we make it work the same as `#big-brother` does. I'm not certain on the specifics, so if you are, please edit this issue. Essentially I believe it uses webhooks.

# Motivation

ELA thought it'd be interesting. Everyone agreed with that.

**Comment by lemonsaurus** [comment]
Channel created. It's called **#dm-log** and the ID is `653713721625018428`

**Comment by MarkKoz** [comment]
This looks like it could almost worth with the existing watch channels base class. However, the main obstacle is that it tracks which users are watched. This affects a few things:

1. Messages are ignored if the user isn't watched
2. The header includes a reason and the actor
3. There is a function to list watched users

I think a flag could be added to not track users but this may make the code messy or seem "patched together", notably the header code. It may be better to use a subclass? I don't think a subclass would have as much redundant code as it first would seem. The base class would have no tracking stuff and the subclass would. 

Does anyone have thoughts on how to go forward with the implementation? Maybe @SebastiaanZ?

**Comment by lemonsaurus** [comment]
I think it sounds messy to subclass WatchChannel here. There's so much stuff in there that we don't need, and several of the key items in it would need to be modified to work for this.

I'm leaning towards a much, much simpler implementation where we just relay messages as they arrive. The motivation behind the async batch message consumption of the watchchannels was because we it to be easier to read the flow of the conversation, instead of having several users conversation blend into one another. I'm not sure that argument really applies to this use case.

I think simply using a webhook with the users avatar and sending the message into the channel will work just fine. It's also a million times easier.

**Comment by lemonsaurus** [comment]
I'll open a PR for this soon.
