### ISSUE TITLE
Duck Pond improvements

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/bot#673]
After merging the duck pond, a few minor bugs and potential for improvements have been uncovered. Please make a PR implementing the following changes:

- [x] A blacklist for channels that duck pond should ignore. This blacklist must contain #duck-pond itself, #announcements, #staff-announcements and #user-event-announcements.
- [x] A command for forcing a message into the duck pond. something like `!duckpond`, alias `!pondify`, `!duckpondify` and `!duckify`
- [ ] New test for making sure it returns early if in a blacklisted channel.
- [x] New test for the command.
- [x] Restrict the `on_raw_reaction_add` handler it so only messages posted by staff members will be duckpondified.
- [x] Prevent the duck pond from relaying the same message more than once during lag by adding a lock.

**Comment by sco1** [comment]
At what level should the new command be role locked to?

**Comment by SebastiaanZ** [comment]
>  A command for forcing a message into the duck pond. something like !duckpond, alias !pondify, !duckpondify and !duckify

What's the use of this? We discussed such a command before, but the argument was that it was only going to be used for historical messages which can easily be relayed using internal eval on the existing `relay_message` method of the class.

**Comment by lemonsaurus** [comment]
I guess the use is to not have to spend time figuring out how to internal eval it.

and role lock would be admins+ imo

**Comment by SebastiaanZ** [comment]
I've added an action point to implement a lock for the message relay.

The reason is that, on occasion, the same message gets relayed more than once due to a race condition: If, for some reason, multiple reaction events fire when we go over the ducking threshold and all of them make it past the "green checkmark check" before a relay is successful, all of them will relay the message as none of them are "aware" that the message is already going to be relayed by one of the other near-simultaneous events.

The solution is straightforward: Add an [`asyncio.Lock`](https://docs.python.org/3/library/asyncio-sync.html#asyncio.Lock) and have the event handler acquire it before it checks for the green checkmark and after it has successfully added the greencheck mark after relaying the message. That way, any additional events have to wait with their green checkmark check until after the previous events has potentially added it.

**Comment by MarkKoz** [comment]
@SebastiaanZ Any updates on this?

**Comment by SebastiaanZ** [comment]
This has been partially implemented. The "New test for making sure it returns early if in a blacklisted channel." was ignored; instead, I removed all tests.
