### ISSUE TITLE
NameError: name 'client' is not defined

### ISSUE THREAD

**Issue by eimul** [python-discord/bot#700]
[I'm using PyCharm]

**CMD**
> Traceback (most recent call last):
>   File "Bird.py", line 4, in <module>
>     class MyClient(discord.Client):
>   File "Bird.py", line 12, in MyClient
>     @client.event
> NameError: name 'client' is not defined

So I'm trying to make my first bot, but I can't even run it.
What am I doing wrong?

![image](https://user-images.githubusercontent.com/58941260/70909671-4061be80-200e-11ea-99f7-fce10d676651.png)

**Comment by SebastiaanZ** [comment]
Hey @eimul,

I think you've ended up in the wrong place. The repository you've created an issue in is the repository for discord bot of [Python Discord](https://pythondiscord.com/), an online Python community. While our bot uses discord.py, we are not affiliated with the library in any way. You can find the repository of the `discord.py` library [here](https://github.com/rapptz/discord.py).

That said, repositories and issues are typically not meant to ask help, but rather to report bugs and discuss potential new features. It's used in the development process of a piece of software and, usually, not a front-end for extended support. I'd advise you to find another platform to ask your questions, like a Discord server (like [ours](https://discord.gg/python) or the [official discord.py discord server](https://discord.gg/r3sSKJJ)) or another platform like [/r/learnpython](https://reddit.com/r/learnreddit) on Reddit.

I'm going to close this issue since it's not related to our specific Discord bot,

Ves
