### ISSUE TITLE
Wiki: document tests and snekbox

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/bot#716]
## Snekbox

- [ ] Mention that snekbox is an optional requirement.
- [ ] Link to documentation for setting up snekbox (the README.md on GitHub is fine).
- [ ] Document configuring `urls.snekbox_eval_api` in the config.

## Tests

- [ ] Show how to run tests and some basics on interpreting coverage results. 
    - This could be a separate article so it can be shared with the site.
- [ ] Link to the README.md in the tests directory on GitHub.
    - Yes, this does describes how run tests but is too specific to the bot so a generic article on how to run tests is a good idea.
    - Consider taking out the more generic parts and making it a new article on the wiki which all projects could use. The bot-specific docs could go in yet another new article.

**Comment by MarkKoz** [comment]
Maybe snekbox should be included in docker-compose 🤔

**Comment by Den4200** [comment]
#988 added snekbox to the docker-compose, so no configuration needs to be done for it anymore.

**Comment by wookie184** [comment]
Pretty much everything here seems to be completed now. We don't describe how to set snekbox up on host, but that's by design since docker is easier.

Tests are mentioned here: https://www.pythondiscord.com/pages/guides/pydis-guides/contributing/bot/#running-tests, we don't have a general guide on site, although there's an issue for documenting testing on site here https://github.com/python-discord/site/issues/678
