### ISSUE TITLE
Unit test for command alias shadowing

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/bot#765]
Currently, it is possible for someone to write a command that shadows an existing alias. Discord will not crash, it will simply short circuit and make the other alias unavailable.

It ought to be possible to add an automated check for this in the form of a unit test. This test might make use of `ast` (which has a means of checking decorator arguments) and then iterate over all cogs to determine if there are any alias duplicates.

This feature would probably be nice to have in seasonalbot, too, so once it's finished it might be nice to port it over there, too.

**Comment by MarkKoz** [comment]
There are two approaches to this:

1. Discover all cog definitions in all modules and check their commands. This is more complex, but it means no cogs ever get instantiated. Modules do get imported so any code defined at the module level would still be executed (usually minor things like defining constants, importing, reading files, etc.)
2. Let the bot be created and load all extensions. The check commands via `bot.commands`. This is very simple and more accurate because commands are not restricted to being defined in cogs (though in practice they are always in cogs). However, this means cogs will be instantiated and they could execute code with potential side effects. How much of a bad thing is this really? I don't know.
3. Parse everything with ast. This seems overly complicated but it does at least guarantee no code will be executed. It probably wouldn't need to discover cogs - it could just parse all files to simplify things.

I've already implemented the first 2 approaches. Now it's a matter of choosing an implementation to go forward with, unless someone thinks ast parsing is really the way forward.

**Comment by lemonsaurus** [comment]
I don't need this to be solved with ast parsing, it was just an idea.

I like approach 1. The benefit of approach 2 seems to be irrelevant for us, and I'm not 100% comfortable with tests actually loading cogs.
