### ISSUE TITLE
Python mailing list channel

### ISSUE THREAD

**Issue by Akarys42** [python-discord/bot#834]
## Abstract
It would be nice to have a channel tracking some of the official python mailing lists, such as python-dev@python.org.

## Specification 
A background task will make the bot fetch from an email API to check if a new email from one of the tracked mailing list have been received, if any email is found, it will post them as an embed to a specific channel inside the server. Some additional content can be put in the embed, such as some informations about the sender, or a jump link to the previous message in the same thread if there is one. Additionally, a new subscribe role for the mailing list could be created, maybe even one per list, and users should be able to add the role to themselves through a command. The appropriate role will be pinged when a new email arrives. 

## Rationale
This feature can be used to be more involved in the cpython development, as these mailing lists are used for things like PEP discutions through python-dev, or even python improvement ideas through python-ideas. Additionally, these email could lead to interesting discutions inside #python-discussion.

Original issue : python-discord/bot#169

**Comment by sco1** [comment]
What mailing list(s) are intended to be followed? What's the general traffic on them, and are we going to stream every message or are we going to do a "digest"? Are we also including the [PEP RSS feed](https://www.python.org/dev/peps/peps.rss/)?

**Comment by jos-b** [comment]
I'm transferring this back to bot because the API driven solution is much more sustainable than the mailgun webhook driven approach.

While the mailman3 API does break when you request all threads we don't need to do that. There is an endpoint which returns the IDs and dates of all recent threads (albeit in a HTML format, but that's nothing that beautifulsoup or any other HTML parsing library can't handle). This document contains a load of `<div>` with an anchor in them with a href like `/archives/list/python-announce-list@python.org/thread/PCZJYTHK6HQUVZMIGSLY3KUECJYWBUNQ/`

All we have to do is get that ID and put that into the API and we get a JSON response: https://mail.python.org/archives/api/list/python-announce-list@python.org/thread/PCZJYTHK6HQUVZMIGSLY3KUECJYWBUNQ/

We do not want every message to be relayed to the channel since that could quite quickly get intense. Instead we should probably just post the link to the start of each thread in a channel.

This approach is much simpler than the mailgun API approach since we'd then have to be parsing links out of HTML emails and still have little information on them while this gives us a range of data which we can work with.

**Comment by jos-b** [comment]
New issue #890
