### ISSUE TITLE
Use role overwrites for new help channel system

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/bot#839]
Copying from the main PR #786:

Are per-member overwrites scalable? Discord may have a limit. Furthermore, there is supposedly client performance degradation with a high amount of overwrites. If this becomes an issue, an overwrite for a role can be used instead. The role would be added/removed from users as needed.

Not 100% decided if it should be switched to a role. Given a total channel limit of 32, there's going to be at most a bit over 32 simultaneous overwrites. That should be fine performance wise. I prefer user overwrites since they're "stealthier" than a new role, but a role would technically be a more robust solution. For now, user overwrites will stay and I'll open an issue to switch to roles.

**Comment by SebastiaanZ** [comment]
Okay, it's time to bump this issue and increase the priority of it. We've now got a couple of days worth of experience with the current system based on permission "overrides" (see note 1) and it's not working well in ways we did not anticipate.

For those not familiar with the current mechanism, we use permission overrides to stop members from claiming a second help channel within 15 minutes of claiming their first (see note 2). We do that by adding a member-specific permission override to the `Help: Available` category that revokes their "send messages" permissions. This should stop them from claiming another channel as they cannot send messages to the available help channels.

An essential part of this system is that the available help channels synchronize their permissions with the category, both to make sure that expired overrides are removed and new overrides are added to the channel. Unfortunately, despite our best efforts to ensure that they do (see e.g., #873), channels stop synchronizing their permissions from time to time or, weirdly, seem to receive permission overrides from some cache that in reality no longer exist in the category.

That's why we want to switch to a role-based system: It means that the category permissions stay consistent over time, hopefully preventing channels from going out of sync. Obviously this will now rely on being able to consistently assign and remove roles from members, but let's hope that this will work as expected.

---
Note 1: Permission overrides are actually called [permission **overwrites**](https://discordapp.com/developers/docs/topics/permissions#permission-overwrites) but @lemonsaurus has his own ideas about that.

**Comment by MarkKoz** [comment]
How would it deal with users which leave the guild? The roles do perist in the database but there would not be a way to know if the user's role should be re-added. Since the mapping of channels to users does not currently persist, it will not be possible to determine if the user's help channel went dormant. Should it just drop the role until some persistence is implemented?

**Comment by SebastiaanZ** [comment]
I think it's fine for now to not persist the roles. It's a role that a user should have for a maximum of 15 minutes at a time anyway and if people try to abuse the non-persistence by leaving/joining to claim multiple channels (I don't think that will happen often), we can moderate them.

Still, persistence has come up a couple of times now for different elements of the help channel system; we should evaluate in due time if and how we're going to tackle that. Once such persistence gets implemented, we could add this to the considerations.

**Comment by SebastiaanZ** [comment]
I've added a role (`Help Cooldown - 699189276025421825`) and set the appropriate permissions on the category.

**Comment by MarkKoz** [comment]
Just an update: I've not made too much progress yet since it turned out to be a busy week for me. I am still planning on working on it once I am not so busy.
