### ISSUE TITLE
Detecting bad words in nicknames

### ISSUE THREAD

**Issue by F4zii** [python-discord/bot#856]
## Description
Since the management decided that we don't care about detecting names which are hard to mention
I changed this issue to solve something different - Bad word detection in our members nicknames.

This system will contain some checks that will be triggered on the event `on_message`, the display_name of the message author will be checked, and if it contains bad words, will be reported or logged.

The checks should be fast and simple to prevent long and heavy calculations that are triggered on each message, but we can expand them to fit our needs.

### Solution
**This system should be implemented as part of the Filtering cog, especially considering the overlap between this and the regex filter (formerly word and token filter).**

We will be using REGEX (Can use the same wordlists we have in the regex filters.) to detect bad words in the members `display_name` (If they have a nice nickname and an awful username, we don't care.)

This should be detected in the event `on_message`, but we want a long cooldown so we don't get notified that often - maybe 3 days.

There is no need to ping moderators about this when this filter triggers. This will be a pingless alert.

The correct channel to deliver this to is #mod-alerts (ID: 473092532147060736)

**Comment by ChillFish8** [comment]
Think a good idea would be to check if the user has any Unicode, to begin with, *before* checking how many ASCII characters they have. I would just require a simple check if their entire name is ASCII why bother counting it. Just reduces the number of times calling a loop, altho minor.

**Comment by ikuyarihS** [comment]
The check for any Unicode by itself requires a loop over the string, so in that light might as well reduce it to a single loop of counting how many mentionable `alnum` in my opinion.

The deal breaker will be how we can make it not spammy, so it will trigger once per user per day perhaps.

**Comment by ChillFish8** [comment]
wouldn't just `<name>isascii()` work for skipping over that loop? if the username is `MyUsername#6621` it will be true, so we could just do `if not <name>isascii()` then check using the loop

**Comment by lemonsaurus** [comment]
Okay, so I've discussed this with the admins and moderators, and we have several comments. @F4zii Please use these comments to reformulate the original issue text and change what this issue is going to solve.

1. We don't care about detecting names which are hard to mention. It's overkill, todays current system works fine. Let's not do that.
2. However, we might want to detect nicknames that have bad words in them. You can use the same wordlists we have in the regex filters.
3. On that note, this should be implemented as part of the Filtering cog, especially considering the overlap between this and the regex filter (formerly word and token filter).
4. This should be detected on_message, but we want a long cooldown so we don't get notified that often - maybe 3 days.
5. There is no need to ping moderators about this when this filter triggers. This will be a pingless alert.
6. The correct channel to deliver this to is #mod-alerts (ID: 473092532147060736)
7. Only check the users display_name, not their username. If they have a nice nickname and an awful username, we don't care.

Please pivot this issue to incorporate all of these directions, and then you have my approval.

**Comment by F4zii** [comment]
About the cooldown itself @lemonsaurus
the check cooldown will be per user ? or just the cooldown of being notified?

**Comment by lemonsaurus** [comment]
per user, yeah. We don't want to be notified of the same user every time they send a message, right? that would just be spam.

**Comment by ChillFish8** [comment]
Could use just some simple dictionary with a timestamp to keep it quick and just check if timestamp diffrence is past a certain point

**Comment by lemonsaurus** [comment]
Something like that. Honestly, cooldowns are a solved problem in the bot, so just do it however we're doing it in other cogs. Ideally in a DRY way.

**Comment by Multivalence** [comment]
Maybe a warning over dm or in channel could be issued to the user with the inappropriate nickname as well?

**Comment by lemonsaurus** [comment]
> Maybe a warning over dm or in channel could be issued to the user with the inappropriate nickname as well?

This sounds like automoderation, which we don't want to do. Our bad word filter has false positives, and I don't want it DMing users when that happens. It's better to let our moderators make these kinds of decisions.

**Comment by ks129** [comment]
I think this should listen for `on_member_update` event, not `on_message` because `on_message` will be called too much. `on_member_update` should check is `display_name` changed and when it is, do check.
