### ISSUE TITLE
Feature: !undormant

### ISSUE THREAD

**Issue by kosayoda** [python-discord/bot#879]
Sometimes channels get accidentally made dormant by staff. This command will undormant the channel and put it back in occupied pool.

Relevant details:
- Permission: Helper+
- Suggested Aliases: `!open`, `!reopen`

**Comment by TeamSpen210** [comment]
Where would this be entered? Currently dormant channels are read-only for `Helper`, so that would need to be altered as well.

**Comment by lemonsaurus** [comment]
That won't be a problem. We can give Helpers write permissions in this category.

**Comment by aeros** [comment]
+1 for the `!open` alias. I typically use `!close` for setting channels as dormant, so `!open` would be the easiest to remember.

**Comment by Den4200** [comment]
I can see this as quite useful, since I've seen a few times where people wanted to answer something from a dormant channel but had to use a new available channel instead.

I also like the `!open` alias, but that would conflict with our `!open` tag.

**Comment by MarkKoz** [comment]
How about extending this to all users? If their channel goes dormant and no one else has used it yet, they would be able to reclaim it. This may be useful if a channel is accidentally closed (even by the claimant). They may have unexpected follow up questions or find out shortly after their issue isn't solved after all.

This could be abused but it's no worse than users sending junk messages to keep their channel open. The amount of channels in the dormant pool shouldn't see a decrease since users would have otherwise claimed a new channel anyway. Furthermore, needing to re-open a channel is a relatively rare situation.

Given the cog is already keeping track of claimants for channels, this feature shouldn't be difficult to implement. It should just know which channel was theirs without needing an explicit argument. Since users don't have permissions to type in dormant channels, they'd have to do run the command in another channel like `#bot-commands`. Invoking it in a different channel is not the greatest experience but I think it's better than having nothing. I'm not that concerned that it makes the system more complicated as this won't be a prominent feature nor will it be used often.

**Comment by SebastiaanZ** [comment]
I like the idea. We may see some people being frustrated by their old channel having gone back into circulation, but there are obviously limits to what we can do.

> Since users don't have permissions to type in dormant channels, they'd have to do run the command in another channel like #bot-commands. Invoking it in a different channel is not the greatest experience but I think it's better than having nothing. I'm not that concerned that it makes the system more complicated as this won't be a prominent feature nor will it be used often.

Not having "send messages" permissions in the dormant channels was my main concern when the idea was brought up before. I think this is probably the best we can do without having to resort to things like permission overwrites. Overwrites may work, but would complicate the system and it may cause us to end up in API/sync issues again (although we'd not be relying on category synchronization in this case).

**Comment by MarkKoz** [comment]
Overwrites could work and we still have code that can be repurposed for it. It also has the advantage of being persistent. Sine categories aren't in the mix, it sounds more promising. However, I wouldn't be convinced and willing to invest in the approach without first testing to confirm it won't be buggy.

That being said, allowing them to type in a dormant channel introduces the problem of not wanting them to type anything besides the open command. It could delete messages like the verification channel does, but that doesn't seem like a great user experience in this case. 

Furthermore, users may not even realise their channel has been moved to dormant. Let's face it, many won't read the dormant embed. I think currently, the lack of permissions is a big indication of that or it at least draws their attention to something having changed.

I'm willing to explore overwrites more but I'm fine with having users invoke it in a different channel.

**Comment by SebastiaanZ** [comment]
The concerns you raise are valid and I think I agree with you that the permissions play a big role in communicating that a channel is now dormant. Let's go with the out-of-channel command for now.

**Comment by MarkKoz** [comment]
This is actually tricky to implement since it's not possible to remove arbitrary items from the channel queue. It uses an `asyncio.Queue` so it can block and wait until a channel becomes dormant. I'm sure there are ways to accomplish that without the queue, but they probably aren't as elegant.

There would also be a race condition between re-opening a channel and the channel being moved to available, which seems especially troublesome if a coroutine is waiting for a channel to go dormant so it can fill in the available slot.

**Comment by Xithrius** [comment]
@MarkKoz do you think we should continue with implementing this, or would it be too messy?

I'm not sure if this feature is *completely* necessary. It would be useful if someone accidentally let their channel go dormant to retrieve it to continue, but we may have to set a limit on how many times you can revive.

**Comment by MarkKoz** [comment]
It could lock everything and rebuild the queue without the channel, but maybe a separate data structure to keep track of which channels to skip in the queue would suffice. In any case, the implementation of this has some nuance due to race conditions, so whoever implements this will have to keep that in mind.

**Comment by ChrisLovering** [comment]
This is something we've discussed with the new help channel style and haven't come to a good solution for.

If discord removes interaction limitations with locked threads, it could be something we look into in future.
