### ISSUE TITLE
Claimant doesn't exist in cache when checking if help channel has been answered

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/bot#912]
## Background

We've been seeing lots of `KeyError` exceptions occur in groups at intervals of 3-4 hours. A log sample can be found here: https://paste.pythondiscord.com/uzokiserux.py

These errors happen every time a new message is sent in an occupied channel. The `on_message` listener calls a function to check if a channel has been answered (i.e. someone other than the claimant has typed something).

## Analysis

The `check_for_answer` only attempts to get the claimant if

1. The channel is in the in use category
2. The channel exists in the `unanswered` dictionary

In order for a channel to be in use, a claimant must exist. However, one will not exist if the bot restarts due to lack of persistent storage currently. That being said, the same will happen to the `unanswered` dictionary. Therefore, neither `unanswered` nor `help_channel_claimants` will contain anything after a bot restart. This rules out lack of persistent storage being the cause.

Both aforementioned dictionaries are set when a channel is claimed, as can be seen [here](https://github.com/python-discord/bot/blob/master/bot/cogs/help_channels.py#L654-L659). `unanswered` is set after `help_channel_claimants`. In fact, this is the only place `unanswered` is modified besides in `check_for_answer`. This means that if a key exists in `unanswered`, it must exist in `help_channel_claimants` because the latter must have already been set in order for the former to exist.

There is one exception, and that's when the close command deletes the key from `help_channel_claimants`. However, it makes the channel dormant right after. `check_for_answer` wouldn't trigger for a dormant channel. In fact, it can be observed in the exception logs that the channel has the ID of the in use category. So for a brief moment between the key being deleted and the channel being moved, it could cause a `KeyError` if a user squeezes in a message. Given there are lots of these errors, this situation is not the case.

The only conclusion I can make is that **the close command deleted the key but failed to make the channel dormant**. In any case, I think the deletion of the key in the close command plays an important role in this issue because otherwise, as I have previously established, `unanswered` cannot have the key unless `help_channel_claimants` has it too.

**Comment by Numerlor** [comment]
Encountered this locally and getting the error every time `!close` is invoked.
With trace logging the issue seems to be `on_message` for the invokation message being received and then the channel moved *after* that happens.
After adding a few additional logging points added the logs look like this
https://paste.fuelrats.com/ecekeratas.txt

With call order like this the channel gets removed from from `help_channel_claimants` but remains in `unanswered`. Then the category check passes because the message was still in the in use category when `on_message` was received and processed; after that an access of the `channel` key is attempted and fails with the above error.

I don't know if that was the actual cause for the deployed bot as it happens always instead of intermittently but hope it provides some insight. Moving the move to dormant to the start of the command didn't have an effect because the move takes about 500ms

**Comment by MarkKoz** [comment]
Thanks for looking into it. That makes more sense than my conclusion. I think we should use proper locks for the command rather than relying on the claimant being deleted from the dict. I was already looking into using locks but haven't gotten _too_ far. I was thinking each channel should have its own lock. I've already made a change locally to group channel data into a dataclass rather than many dictionaries, so the lock could be stored there too.

**Comment by MarkKoz** [comment]
This was fixed by 63f5028641e9b78c61d3bcfe3bbaa6f80c8a288a but I will leave this open to try to address the race condition.

**Comment by MarkKoz** [comment]
#1346 should have addressed any outstanding race conditions.
