### ISSUE TITLE
Include more text formats in the antimalware filter

### ISSUE THREAD

**Issue by Numerlor** [python-discord/bot#943]
The #925 PR got merged recently, but only handles `.txt` files;
this leaves out other common shared file types like `.csv` to be handled using the generic filter message, which doesn't mention the paste service as an alternative to direct file upload and sometimes results in people circumventing the filter.

**Comment by Savant-Dev** [comment]
The inclusion of `.csv`, `.json` and like file-types was discussed heavily in #meta around the time #925 was being solved. The consensus was that the primary purpose of that PR was to fix Discord's auto-conversion of long messages (2000 chars >) 

Perhaps, instead of trying to include other file-types in the `.txt` filter you could simply revise the existing embed under the `else` to include the paste link?
![Screenshot from 2020-05-16 02-31-08](https://user-images.githubusercontent.com/64629111/82112698-5ee2f780-971d-11ea-9fab-fdba02849dca.png)

**Comment by Numerlor** [comment]
Including it in the geneic embed wouldn't be helpful for the binary types the filter is intended for so I don't think it's worth putting it there.

The discussions I remember about csv etc. was about excluding the from the filters completely; not about adding them to the new handler. The original issue did also talk about a list of text extensions

**Comment by Xithrius** [comment]
I think this feature should be implemented, and I'll probably just go ahead and do it.

Any other suggestions for file formats that would be zapped but still given the suggestion for our paste service?
