### ISSUE TITLE
Automation for the #incidents channel

### ISSUE THREAD

**Issue by kwzrd** [python-discord/bot#992]
Previously tracked here: https://github.com/python-discord/organisation/issues/255

# Basic proposal

Recently, we have introduced a new `#incidents` channel, which now hosts all incident reporting from the `@Helpers+` team. Moderators are encouraged to use 3 status emojis to signal their involvement, if any, with the incident at hand:

![image](https://user-images.githubusercontent.com/44734341/83978961-52605200-a90b-11ea-9d32-cf0d14026fdb.png)

To make things easier for moderators, we have decided to introduce automation to the emoji signaling system. The idea is to have the bot automatically leave the 3 possible emoji choices under each new message - moderators can then simply click the one they wish to choose. The bot then clears the remaining emojis. Should the moderator un-select their choice, the bot adds the 3 choices again, e.g. to allow a smooth transition from *investigating* to *actioned*.

### Considerations

The desired behaviour in situations where *multiple* moderators react is currently undefined. I haven't put an extensive amount of thought to this, so there may be additional edge cases, but one of the questions we should ask ourselves is what happens if 2 moderators select a reaction, and subsequently, what happens if one un-selects.

The bot can either:
1. Ignore the situation - as long as there is at least *one* react, no bot action is needed
2. Clear *all* reactions, add the 3 options again, and await further input

I'm currently leaning towards option 2, since that will allow, for example, clearing another user's "forgotten" / invalid signal. It would be good to hear others' opinions on this, since we touched on the problem during the staff meet, but afaik haven't come to a definitive answer.

# Advanced features

Additionally, the following functionality (and more) could be supported.

### Incident clearing

Since the bot can now determine the status of any incident, it will also be possible to clear solved incidents (after some period of time, or upon an actioned / unactioned react), like we currently do using internal eval on-demand. It is also possible to relay solved incidents into a read-only channel (a webhook would be nice) for archiving purposes - this channel should probably be visible to `@Helpers`, so that they can review the status of their report despite it being cleared from the active `#incidents` pool.

Implementation-wise, the most important question here is how to schedule the incident clearing. If the incident gets cleared instantly, the first actioned / unactioned react will be definitive. That would actually solve the previously mentioned issues with multi-react, but is that what we want?

### Highlighting unresolved incidents

Incidents that have *not* been resolved (i.e. reacted to with either tick or cross) should be highlighted after some time. The bot could, for example, ping `@Moderators` with a summary of unresolved incidents, and links to them. This could be done in `#mods`, or `#incidents` directly (it could probably be treated as an incident of its own, cleared with a react as usual).

# Afterword

I'm interested in implementing this, but I'd like us to continue the conversation about exactly how we'd like it to behave. Let's make sure we don't introduce a system that we will end up fighting - its primary and perhaps only purpose is to make helpers' and mods' lives easier. I've tried to highlight a few unanswered questions, and I'd be really happy to hear others' opinions on them.

**Comment by j03b** [comment]
We've discussed some minor updates to the interface in the dev-core channel.

When a report is created the investigating icon <img src="https://cdn.discordapp.com/emojis/714224190928191551.png?v=1" height="15" style="vertical-align: middle;"/> is added as a reaction to the report.

<img width="921" alt="Screenshot 2020-06-09 at 00 12 26" src="https://user-images.githubusercontent.com/20439493/84089052-e7d01480-a9e5-11ea-943e-933df44c4c81.png">

Once a moderator clicks this reaction to mark an incident as being under review two extra reaction, <img src="https://cdn.discordapp.com/emojis/714221559279255583.png?v=1" height="15" style="vertical-align: middle;"/> and <img src="https://cdn.discordapp.com/emojis/714223099645526026.png?v=1" height="15" style="vertical-align: middle;"/>, are added.

Upon any moderator clicking these icons the incident will be relayed to the archive and deleted.

## Additional cases

### Helper adds a reaction

Reactions added by non-moderation staff will be removed and ignored by the bot.

### Moderator wants to revert issue to non-investigating state

Once a report is in the investigating state it will look like this:

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/20439493/84088898-84de7d80-a9e5-11ea-8aec-1df1b187f5e4.png">

In order to reset this to the original menu, the original moderator can remove the <img src="https://cdn.discordapp.com/emojis/714224190928191551.png?v=1" height="15" style="vertical-align: middle;"/> reaction.

Alternatively another moderator can *add* a <img src="https://cdn.discordapp.com/emojis/714224190928191551.png?v=1" height="15" style="vertical-align: middle;"/> reaction which will clear the reaction on the incident and reset it to the initial state:

<img width="920" alt="Screenshot 2020-06-09 at 00 12 08" src="https://user-images.githubusercontent.com/20439493/84089045-dd157f80-a9e5-11ea-8636-f824015dfe06.png">

An interactive example of the whole interaction from a **single moderator perspective** can be found [here](https://www.figma.com/proto/6L3So5weNg7rsuNaf7ZGv7/Incidents-channel-reactions?node-id=1%3A2&viewport=341%2C522%2C1.0368454456329346&scaling=contain)
